//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.PromocionConjunto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", ConfigurationName="PromocionConjunto.PromocionConjuntoWS")]
    public interface PromocionConjuntoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrar_prom" +
            "ocionesconjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrar_prom" +
            "ocionesconjuntoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(promocion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoResponse mostrar_promocionesconjunto(WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrar_prom" +
            "ocionesconjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrar_prom" +
            "ocionesconjuntoResponse")]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoResponse> mostrar_promocionesconjuntoAsync(WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrar_prom" +
            "ocionesconjuntoactivosRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrar_prom" +
            "ocionesconjuntoactivosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(promocion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosResponse mostrar_promocionesconjuntoactivos(WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrar_prom" +
            "ocionesconjuntoactivosRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrar_prom" +
            "ocionesconjuntoactivosResponse")]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosResponse> mostrar_promocionesconjuntoactivosAsync(WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/helloRequest" +
            "", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/helloRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(promocion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.PromocionConjunto.helloResponse hello(WearDropWA.PromocionConjunto.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/helloRequest" +
            "", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/helloRespons" +
            "e")]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.helloResponse> helloAsync(WearDropWA.PromocionConjunto.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/insertarProm" +
            "ocionConjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/insertarProm" +
            "ocionConjuntoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(promocion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.PromocionConjunto.insertarPromocionConjuntoResponse insertarPromocionConjunto(WearDropWA.PromocionConjunto.insertarPromocionConjuntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/insertarProm" +
            "ocionConjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/insertarProm" +
            "ocionConjuntoResponse")]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.insertarPromocionConjuntoResponse> insertarPromocionConjuntoAsync(WearDropWA.PromocionConjunto.insertarPromocionConjuntoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/eliminarProm" +
            "ocionConjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/eliminarProm" +
            "ocionConjuntoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(promocion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.PromocionConjunto.eliminarPromocionConjuntoResponse eliminarPromocionConjunto(WearDropWA.PromocionConjunto.eliminarPromocionConjuntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/eliminarProm" +
            "ocionConjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/eliminarProm" +
            "ocionConjuntoResponse")]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.eliminarPromocionConjuntoResponse> eliminarPromocionConjuntoAsync(WearDropWA.PromocionConjunto.eliminarPromocionConjuntoRequest request);
        
        // CODEGEN: El parámetro 'idDesc' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/insertarPren" +
            "daConjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/insertarPren" +
            "daConjuntoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(promocion))]
        WearDropWA.PromocionConjunto.insertarPrendaConjuntoResponse insertarPrendaConjunto(WearDropWA.PromocionConjunto.insertarPrendaConjuntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/insertarPren" +
            "daConjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/insertarPren" +
            "daConjuntoResponse")]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.insertarPrendaConjuntoResponse> insertarPrendaConjuntoAsync(WearDropWA.PromocionConjunto.insertarPrendaConjuntoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/obtenerPorId" +
            "ConjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/obtenerPorId" +
            "ConjuntoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(promocion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.PromocionConjunto.obtenerPorIdConjuntoResponse obtenerPorIdConjunto(WearDropWA.PromocionConjunto.obtenerPorIdConjuntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/obtenerPorId" +
            "ConjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/obtenerPorId" +
            "ConjuntoResponse")]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.obtenerPorIdConjuntoResponse> obtenerPorIdConjuntoAsync(WearDropWA.PromocionConjunto.obtenerPorIdConjuntoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrarConju" +
            "ntoXPrendaRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrarConju" +
            "ntoXPrendaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(promocion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaResponse mostrarConjuntoXPrenda(WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrarConju" +
            "ntoXPrendaRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/mostrarConju" +
            "ntoXPrendaResponse")]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaResponse> mostrarConjuntoXPrendaAsync(WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/modificarPro" +
            "mocionConjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/modificarPro" +
            "mocionConjuntoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(promocion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.PromocionConjunto.modificarPromocionConjuntoResponse modificarPromocionConjunto(WearDropWA.PromocionConjunto.modificarPromocionConjuntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/modificarPro" +
            "mocionConjuntoRequest", ReplyAction="http://promociones.services.weardrop.pucp.edu.pe/PromocionConjuntoWS/modificarPro" +
            "mocionConjuntoResponse")]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.modificarPromocionConjuntoResponse> modificarPromocionConjuntoAsync(WearDropWA.PromocionConjunto.modificarPromocionConjuntoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/")]
    public partial class promocionConjunto : promocion {
        
        private double porcentajePromocionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double porcentajePromocion {
            get {
                return this.porcentajePromocionField;
            }
            set {
                this.porcentajePromocionField = value;
                this.RaisePropertyChanged("porcentajePromocion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(promocionConjunto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/")]
    public abstract partial class promocion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idPromocionField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPromocion {
            get {
                return this.idPromocionField;
            }
            set {
                this.idPromocionField = value;
                this.RaisePropertyChanged("idPromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/")]
    public partial class vigencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idVigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idVigencia {
            get {
                return this.idVigenciaField;
            }
            set {
                this.idVigenciaField = value;
                this.RaisePropertyChanged("idVigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrar_promocionesconjunto", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrar_promocionesconjuntoRequest {
        
        public mostrar_promocionesconjuntoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrar_promocionesconjuntoResponse", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrar_promocionesconjuntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.PromocionConjunto.promocionConjunto[] @return;
        
        public mostrar_promocionesconjuntoResponse() {
        }
        
        public mostrar_promocionesconjuntoResponse(WearDropWA.PromocionConjunto.promocionConjunto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrar_promocionesconjuntoactivos", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrar_promocionesconjuntoactivosRequest {
        
        public mostrar_promocionesconjuntoactivosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrar_promocionesconjuntoactivosResponse", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrar_promocionesconjuntoactivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.PromocionConjunto.promocionConjunto[] @return;
        
        public mostrar_promocionesconjuntoactivosResponse() {
        }
        
        public mostrar_promocionesconjuntoactivosResponse(WearDropWA.PromocionConjunto.promocionConjunto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPromocionConjunto", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPromocionConjuntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.PromocionConjunto.promocionConjunto datProm;
        
        public insertarPromocionConjuntoRequest() {
        }
        
        public insertarPromocionConjuntoRequest(WearDropWA.PromocionConjunto.promocionConjunto datProm) {
            this.datProm = datProm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPromocionConjuntoResponse", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPromocionConjuntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPromocionConjuntoResponse() {
        }
        
        public insertarPromocionConjuntoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPromocionConjunto", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPromocionConjuntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProm;
        
        public eliminarPromocionConjuntoRequest() {
        }
        
        public eliminarPromocionConjuntoRequest(int idProm) {
            this.idProm = idProm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPromocionConjuntoResponse", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPromocionConjuntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPromocionConjuntoResponse() {
        }
        
        public eliminarPromocionConjuntoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPrendaConjunto", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPrendaConjuntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("idPrendas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] idPrendas;
        
        public insertarPrendaConjuntoRequest() {
        }
        
        public insertarPrendaConjuntoRequest(int idDesc, int[] idPrendas) {
            this.idDesc = idDesc;
            this.idPrendas = idPrendas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPrendaConjuntoResponse", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPrendaConjuntoResponse {
        
        public insertarPrendaConjuntoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdConjunto", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdConjuntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProm;
        
        public obtenerPorIdConjuntoRequest() {
        }
        
        public obtenerPorIdConjuntoRequest(int idProm) {
            this.idProm = idProm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdConjuntoResponse", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdConjuntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.PromocionConjunto.promocionConjunto @return;
        
        public obtenerPorIdConjuntoResponse() {
        }
        
        public obtenerPorIdConjuntoResponse(WearDropWA.PromocionConjunto.promocionConjunto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrarConjuntoXPrenda", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrarConjuntoXPrendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPrenda;
        
        public mostrarConjuntoXPrendaRequest() {
        }
        
        public mostrarConjuntoXPrendaRequest(int idPrenda) {
            this.idPrenda = idPrenda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrarConjuntoXPrendaResponse", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrarConjuntoXPrendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.PromocionConjunto.promocionConjunto[] @return;
        
        public mostrarConjuntoXPrendaResponse() {
        }
        
        public mostrarConjuntoXPrendaResponse(WearDropWA.PromocionConjunto.promocionConjunto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPromocionConjunto", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPromocionConjuntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.PromocionConjunto.promocionConjunto datProm;
        
        public modificarPromocionConjuntoRequest() {
        }
        
        public modificarPromocionConjuntoRequest(WearDropWA.PromocionConjunto.promocionConjunto datProm) {
            this.datProm = datProm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPromocionConjuntoResponse", WrapperNamespace="http://promociones.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPromocionConjuntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://promociones.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPromocionConjuntoResponse() {
        }
        
        public modificarPromocionConjuntoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PromocionConjuntoWSChannel : WearDropWA.PromocionConjunto.PromocionConjuntoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PromocionConjuntoWSClient : System.ServiceModel.ClientBase<WearDropWA.PromocionConjunto.PromocionConjuntoWS>, WearDropWA.PromocionConjunto.PromocionConjuntoWS {
        
        public PromocionConjuntoWSClient() {
        }
        
        public PromocionConjuntoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PromocionConjuntoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromocionConjuntoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromocionConjuntoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoResponse WearDropWA.PromocionConjunto.PromocionConjuntoWS.mostrar_promocionesconjunto(WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoRequest request) {
            return base.Channel.mostrar_promocionesconjunto(request);
        }
        
        public WearDropWA.PromocionConjunto.promocionConjunto[] mostrar_promocionesconjunto() {
            WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoRequest inValue = new WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoRequest();
            WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoResponse retVal = ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).mostrar_promocionesconjunto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoResponse> WearDropWA.PromocionConjunto.PromocionConjuntoWS.mostrar_promocionesconjuntoAsync(WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoRequest request) {
            return base.Channel.mostrar_promocionesconjuntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoResponse> mostrar_promocionesconjuntoAsync() {
            WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoRequest inValue = new WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoRequest();
            return ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).mostrar_promocionesconjuntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosResponse WearDropWA.PromocionConjunto.PromocionConjuntoWS.mostrar_promocionesconjuntoactivos(WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosRequest request) {
            return base.Channel.mostrar_promocionesconjuntoactivos(request);
        }
        
        public WearDropWA.PromocionConjunto.promocionConjunto[] mostrar_promocionesconjuntoactivos() {
            WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosRequest inValue = new WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosRequest();
            WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosResponse retVal = ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).mostrar_promocionesconjuntoactivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosResponse> WearDropWA.PromocionConjunto.PromocionConjuntoWS.mostrar_promocionesconjuntoactivosAsync(WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosRequest request) {
            return base.Channel.mostrar_promocionesconjuntoactivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosResponse> mostrar_promocionesconjuntoactivosAsync() {
            WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosRequest inValue = new WearDropWA.PromocionConjunto.mostrar_promocionesconjuntoactivosRequest();
            return ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).mostrar_promocionesconjuntoactivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.PromocionConjunto.helloResponse WearDropWA.PromocionConjunto.PromocionConjuntoWS.hello(WearDropWA.PromocionConjunto.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WearDropWA.PromocionConjunto.helloRequest inValue = new WearDropWA.PromocionConjunto.helloRequest();
            inValue.name = name;
            WearDropWA.PromocionConjunto.helloResponse retVal = ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.helloResponse> WearDropWA.PromocionConjunto.PromocionConjuntoWS.helloAsync(WearDropWA.PromocionConjunto.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.helloResponse> helloAsync(string name) {
            WearDropWA.PromocionConjunto.helloRequest inValue = new WearDropWA.PromocionConjunto.helloRequest();
            inValue.name = name;
            return ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.PromocionConjunto.insertarPromocionConjuntoResponse WearDropWA.PromocionConjunto.PromocionConjuntoWS.insertarPromocionConjunto(WearDropWA.PromocionConjunto.insertarPromocionConjuntoRequest request) {
            return base.Channel.insertarPromocionConjunto(request);
        }
        
        public int insertarPromocionConjunto(WearDropWA.PromocionConjunto.promocionConjunto datProm) {
            WearDropWA.PromocionConjunto.insertarPromocionConjuntoRequest inValue = new WearDropWA.PromocionConjunto.insertarPromocionConjuntoRequest();
            inValue.datProm = datProm;
            WearDropWA.PromocionConjunto.insertarPromocionConjuntoResponse retVal = ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).insertarPromocionConjunto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.insertarPromocionConjuntoResponse> WearDropWA.PromocionConjunto.PromocionConjuntoWS.insertarPromocionConjuntoAsync(WearDropWA.PromocionConjunto.insertarPromocionConjuntoRequest request) {
            return base.Channel.insertarPromocionConjuntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.insertarPromocionConjuntoResponse> insertarPromocionConjuntoAsync(WearDropWA.PromocionConjunto.promocionConjunto datProm) {
            WearDropWA.PromocionConjunto.insertarPromocionConjuntoRequest inValue = new WearDropWA.PromocionConjunto.insertarPromocionConjuntoRequest();
            inValue.datProm = datProm;
            return ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).insertarPromocionConjuntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.PromocionConjunto.eliminarPromocionConjuntoResponse WearDropWA.PromocionConjunto.PromocionConjuntoWS.eliminarPromocionConjunto(WearDropWA.PromocionConjunto.eliminarPromocionConjuntoRequest request) {
            return base.Channel.eliminarPromocionConjunto(request);
        }
        
        public int eliminarPromocionConjunto(int idProm) {
            WearDropWA.PromocionConjunto.eliminarPromocionConjuntoRequest inValue = new WearDropWA.PromocionConjunto.eliminarPromocionConjuntoRequest();
            inValue.idProm = idProm;
            WearDropWA.PromocionConjunto.eliminarPromocionConjuntoResponse retVal = ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).eliminarPromocionConjunto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.eliminarPromocionConjuntoResponse> WearDropWA.PromocionConjunto.PromocionConjuntoWS.eliminarPromocionConjuntoAsync(WearDropWA.PromocionConjunto.eliminarPromocionConjuntoRequest request) {
            return base.Channel.eliminarPromocionConjuntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.eliminarPromocionConjuntoResponse> eliminarPromocionConjuntoAsync(int idProm) {
            WearDropWA.PromocionConjunto.eliminarPromocionConjuntoRequest inValue = new WearDropWA.PromocionConjunto.eliminarPromocionConjuntoRequest();
            inValue.idProm = idProm;
            return ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).eliminarPromocionConjuntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.PromocionConjunto.insertarPrendaConjuntoResponse WearDropWA.PromocionConjunto.PromocionConjuntoWS.insertarPrendaConjunto(WearDropWA.PromocionConjunto.insertarPrendaConjuntoRequest request) {
            return base.Channel.insertarPrendaConjunto(request);
        }
        
        public void insertarPrendaConjunto(int idDesc, int[] idPrendas) {
            WearDropWA.PromocionConjunto.insertarPrendaConjuntoRequest inValue = new WearDropWA.PromocionConjunto.insertarPrendaConjuntoRequest();
            inValue.idDesc = idDesc;
            inValue.idPrendas = idPrendas;
            WearDropWA.PromocionConjunto.insertarPrendaConjuntoResponse retVal = ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).insertarPrendaConjunto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.insertarPrendaConjuntoResponse> WearDropWA.PromocionConjunto.PromocionConjuntoWS.insertarPrendaConjuntoAsync(WearDropWA.PromocionConjunto.insertarPrendaConjuntoRequest request) {
            return base.Channel.insertarPrendaConjuntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.insertarPrendaConjuntoResponse> insertarPrendaConjuntoAsync(int idDesc, int[] idPrendas) {
            WearDropWA.PromocionConjunto.insertarPrendaConjuntoRequest inValue = new WearDropWA.PromocionConjunto.insertarPrendaConjuntoRequest();
            inValue.idDesc = idDesc;
            inValue.idPrendas = idPrendas;
            return ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).insertarPrendaConjuntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.PromocionConjunto.obtenerPorIdConjuntoResponse WearDropWA.PromocionConjunto.PromocionConjuntoWS.obtenerPorIdConjunto(WearDropWA.PromocionConjunto.obtenerPorIdConjuntoRequest request) {
            return base.Channel.obtenerPorIdConjunto(request);
        }
        
        public WearDropWA.PromocionConjunto.promocionConjunto obtenerPorIdConjunto(int idProm) {
            WearDropWA.PromocionConjunto.obtenerPorIdConjuntoRequest inValue = new WearDropWA.PromocionConjunto.obtenerPorIdConjuntoRequest();
            inValue.idProm = idProm;
            WearDropWA.PromocionConjunto.obtenerPorIdConjuntoResponse retVal = ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).obtenerPorIdConjunto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.obtenerPorIdConjuntoResponse> WearDropWA.PromocionConjunto.PromocionConjuntoWS.obtenerPorIdConjuntoAsync(WearDropWA.PromocionConjunto.obtenerPorIdConjuntoRequest request) {
            return base.Channel.obtenerPorIdConjuntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.obtenerPorIdConjuntoResponse> obtenerPorIdConjuntoAsync(int idProm) {
            WearDropWA.PromocionConjunto.obtenerPorIdConjuntoRequest inValue = new WearDropWA.PromocionConjunto.obtenerPorIdConjuntoRequest();
            inValue.idProm = idProm;
            return ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).obtenerPorIdConjuntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaResponse WearDropWA.PromocionConjunto.PromocionConjuntoWS.mostrarConjuntoXPrenda(WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaRequest request) {
            return base.Channel.mostrarConjuntoXPrenda(request);
        }
        
        public WearDropWA.PromocionConjunto.promocionConjunto[] mostrarConjuntoXPrenda(int idPrenda) {
            WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaRequest inValue = new WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaRequest();
            inValue.idPrenda = idPrenda;
            WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaResponse retVal = ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).mostrarConjuntoXPrenda(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaResponse> WearDropWA.PromocionConjunto.PromocionConjuntoWS.mostrarConjuntoXPrendaAsync(WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaRequest request) {
            return base.Channel.mostrarConjuntoXPrendaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaResponse> mostrarConjuntoXPrendaAsync(int idPrenda) {
            WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaRequest inValue = new WearDropWA.PromocionConjunto.mostrarConjuntoXPrendaRequest();
            inValue.idPrenda = idPrenda;
            return ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).mostrarConjuntoXPrendaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.PromocionConjunto.modificarPromocionConjuntoResponse WearDropWA.PromocionConjunto.PromocionConjuntoWS.modificarPromocionConjunto(WearDropWA.PromocionConjunto.modificarPromocionConjuntoRequest request) {
            return base.Channel.modificarPromocionConjunto(request);
        }
        
        public int modificarPromocionConjunto(WearDropWA.PromocionConjunto.promocionConjunto datProm) {
            WearDropWA.PromocionConjunto.modificarPromocionConjuntoRequest inValue = new WearDropWA.PromocionConjunto.modificarPromocionConjuntoRequest();
            inValue.datProm = datProm;
            WearDropWA.PromocionConjunto.modificarPromocionConjuntoResponse retVal = ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).modificarPromocionConjunto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.modificarPromocionConjuntoResponse> WearDropWA.PromocionConjunto.PromocionConjuntoWS.modificarPromocionConjuntoAsync(WearDropWA.PromocionConjunto.modificarPromocionConjuntoRequest request) {
            return base.Channel.modificarPromocionConjuntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.PromocionConjunto.modificarPromocionConjuntoResponse> modificarPromocionConjuntoAsync(WearDropWA.PromocionConjunto.promocionConjunto datProm) {
            WearDropWA.PromocionConjunto.modificarPromocionConjuntoRequest inValue = new WearDropWA.PromocionConjunto.modificarPromocionConjuntoRequest();
            inValue.datProm = datProm;
            return ((WearDropWA.PromocionConjunto.PromocionConjuntoWS)(this)).modificarPromocionConjuntoAsync(inValue);
        }
    }
}
