# === CONFIGURACI\u00d3N DE SEGURIDAD (WEARDROP DB MANAGER) ===

# Llave para la Base de Datos (MySQL)
db.encriptacion.llave=HY5/Bde/s2mFrWn0blGfg1jOpgLbmg+gdRek9gtP13E=

# Nota: El correo aqu\u00ed es opcional, DBManager usualmente no env\u00eda emails.
config.emailOrigen=correoweardrop@gmail.com