# === CONFIGURACI\u00d3N DEL CORREO (WEARDROP BUSINESS) ===

# 1. Tu correo de Gmail (el que usaste para generar la clave)
config.emailOrigen=correoweardrop@gmail.com

# 2. La contrase\u00f1a de 16 letras YA ENCRIPTADA (lo que acabas de generar)
config.passwordEmailOrigen=FYeREoKgd5tLCfNtuRPfI6AkVyLKdZJZq4C53EVZ86U=

# 3. La llave maestra AES (la nueva que se gener\u00f3)
mail.encriptacion.llave=MyRzo1JwJfmh3rhDFDagjA==