//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.ReporteDeInventarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://reportes.services.weardrop.pucp.edu.pe/", ConfigurationName="ReporteDeInventarioWS.ReporteDeInventarioWS")]
    public interface ReporteDeInventarioWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://reportes.services.weardrop.pucp.edu.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://reportes.services.weardrop.pucp.edu.pe/ReporteDeInventarioWS/generarReport" +
            "eDeInventarioRequest", ReplyAction="http://reportes.services.weardrop.pucp.edu.pe/ReporteDeInventarioWS/generarReport" +
            "eDeInventarioResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioResponse generarReporteDeInventario(WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportes.services.weardrop.pucp.edu.pe/ReporteDeInventarioWS/generarReport" +
            "eDeInventarioRequest", ReplyAction="http://reportes.services.weardrop.pucp.edu.pe/ReporteDeInventarioWS/generarReport" +
            "eDeInventarioResponse")]
        System.Threading.Tasks.Task<WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioResponse> generarReporteDeInventarioAsync(WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteDeInventario", WrapperNamespace="http://reportes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteDeInventarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public System.DateTime fecha;
        
        public generarReporteDeInventarioRequest() {
        }
        
        public generarReporteDeInventarioRequest(System.DateTime fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteDeInventarioResponse", WrapperNamespace="http://reportes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteDeInventarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReporteDeInventarioResponse() {
        }
        
        public generarReporteDeInventarioResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteDeInventarioWSChannel : WearDropWA.ReporteDeInventarioWS.ReporteDeInventarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteDeInventarioWSClient : System.ServiceModel.ClientBase<WearDropWA.ReporteDeInventarioWS.ReporteDeInventarioWS>, WearDropWA.ReporteDeInventarioWS.ReporteDeInventarioWS {
        
        public ReporteDeInventarioWSClient() {
        }
        
        public ReporteDeInventarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteDeInventarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteDeInventarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteDeInventarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioResponse WearDropWA.ReporteDeInventarioWS.ReporteDeInventarioWS.generarReporteDeInventario(WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioRequest request) {
            return base.Channel.generarReporteDeInventario(request);
        }
        
        public byte[] generarReporteDeInventario(System.DateTime fecha) {
            WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioRequest inValue = new WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioRequest();
            inValue.fecha = fecha;
            WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioResponse retVal = ((WearDropWA.ReporteDeInventarioWS.ReporteDeInventarioWS)(this)).generarReporteDeInventario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioResponse> WearDropWA.ReporteDeInventarioWS.ReporteDeInventarioWS.generarReporteDeInventarioAsync(WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioRequest request) {
            return base.Channel.generarReporteDeInventarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioResponse> generarReporteDeInventarioAsync(System.DateTime fecha) {
            WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioRequest inValue = new WearDropWA.ReporteDeInventarioWS.generarReporteDeInventarioRequest();
            inValue.fecha = fecha;
            return ((WearDropWA.ReporteDeInventarioWS.ReporteDeInventarioWS)(this)).generarReporteDeInventarioAsync(inValue);
        }
    }
}
