//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.BoletaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/", ConfigurationName="BoletaService.BoletaWS")]
    public interface BoletaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/eliminarBoletaRequest", ReplyAction="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/eliminarBoletaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BoletaService.eliminarBoletaResponse eliminarBoleta(WearDropWA.BoletaService.eliminarBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/eliminarBoletaRequest", ReplyAction="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/eliminarBoletaResponse" +
            "")]
        System.Threading.Tasks.Task<WearDropWA.BoletaService.eliminarBoletaResponse> eliminarBoletaAsync(WearDropWA.BoletaService.eliminarBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/modificarBoletaRequest" +
            "", ReplyAction="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/modificarBoletaRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(comprobanteDePago))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BoletaService.modificarBoletaResponse modificarBoleta(WearDropWA.BoletaService.modificarBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/modificarBoletaRequest" +
            "", ReplyAction="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/modificarBoletaRespons" +
            "e")]
        System.Threading.Tasks.Task<WearDropWA.BoletaService.modificarBoletaResponse> modificarBoletaAsync(WearDropWA.BoletaService.modificarBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/listarTodasBoletasRequ" +
            "est", ReplyAction="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/listarTodasBoletasResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(comprobanteDePago))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BoletaService.listarTodasBoletasResponse listarTodasBoletas(WearDropWA.BoletaService.listarTodasBoletasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/listarTodasBoletasRequ" +
            "est", ReplyAction="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/listarTodasBoletasResp" +
            "onse")]
        System.Threading.Tasks.Task<WearDropWA.BoletaService.listarTodasBoletasResponse> listarTodasBoletasAsync(WearDropWA.BoletaService.listarTodasBoletasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/insertarBoletaRequest", ReplyAction="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/insertarBoletaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(comprobanteDePago))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BoletaService.insertarBoletaResponse insertarBoleta(WearDropWA.BoletaService.insertarBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/insertarBoletaRequest", ReplyAction="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/insertarBoletaResponse" +
            "")]
        System.Threading.Tasks.Task<WearDropWA.BoletaService.insertarBoletaResponse> insertarBoletaAsync(WearDropWA.BoletaService.insertarBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/obtenerBoletaPorIdRequ" +
            "est", ReplyAction="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/obtenerBoletaPorIdResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(comprobanteDePago))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BoletaService.obtenerBoletaPorIdResponse obtenerBoletaPorId(WearDropWA.BoletaService.obtenerBoletaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/obtenerBoletaPorIdRequ" +
            "est", ReplyAction="http://comprobantes.services.weardrop.pucp.edu.pe/BoletaWS/obtenerBoletaPorIdResp" +
            "onse")]
        System.Threading.Tasks.Task<WearDropWA.BoletaService.obtenerBoletaPorIdResponse> obtenerBoletaPorIdAsync(WearDropWA.BoletaService.obtenerBoletaPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarBoleta", WrapperNamespace="http://comprobantes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idBoleta;
        
        public eliminarBoletaRequest() {
        }
        
        public eliminarBoletaRequest(int idBoleta) {
            this.idBoleta = idBoleta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarBoletaResponse", WrapperNamespace="http://comprobantes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarBoletaResponse() {
        }
        
        public eliminarBoletaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/")]
    public partial class boleta : comprobanteDePago {
        
        private string dNIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
                this.RaisePropertyChanged("DNI");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(boleta))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/")]
    public abstract partial class comprobanteDePago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private string[] arregloCorrelativoField;
        
        private string correlativoField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private double iGVField;
        
        private int idComprobanteField;
        
        private string metodoDePagoField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("arregloCorrelativo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] arregloCorrelativo {
            get {
                return this.arregloCorrelativoField;
            }
            set {
                this.arregloCorrelativoField = value;
                this.RaisePropertyChanged("arregloCorrelativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correlativo {
            get {
                return this.correlativoField;
            }
            set {
                this.correlativoField = value;
                this.RaisePropertyChanged("correlativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double IGV {
            get {
                return this.iGVField;
            }
            set {
                this.iGVField = value;
                this.RaisePropertyChanged("IGV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idComprobante {
            get {
                return this.idComprobanteField;
            }
            set {
                this.idComprobanteField = value;
                this.RaisePropertyChanged("idComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string metodoDePago {
            get {
                return this.metodoDePagoField;
            }
            set {
                this.metodoDePagoField = value;
                this.RaisePropertyChanged("metodoDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarBoleta", WrapperNamespace="http://comprobantes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.BoletaService.boleta datBoleta;
        
        public modificarBoletaRequest() {
        }
        
        public modificarBoletaRequest(WearDropWA.BoletaService.boleta datBoleta) {
            this.datBoleta = datBoleta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarBoletaResponse", WrapperNamespace="http://comprobantes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarBoletaResponse() {
        }
        
        public modificarBoletaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasBoletas", WrapperNamespace="http://comprobantes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasBoletasRequest {
        
        public listarTodasBoletasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasBoletasResponse", WrapperNamespace="http://comprobantes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasBoletasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.BoletaService.boleta[] @return;
        
        public listarTodasBoletasResponse() {
        }
        
        public listarTodasBoletasResponse(WearDropWA.BoletaService.boleta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarBoleta", WrapperNamespace="http://comprobantes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.BoletaService.boleta datBoleta;
        
        public insertarBoletaRequest() {
        }
        
        public insertarBoletaRequest(WearDropWA.BoletaService.boleta datBoleta) {
            this.datBoleta = datBoleta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarBoletaResponse", WrapperNamespace="http://comprobantes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarBoletaResponse() {
        }
        
        public insertarBoletaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerBoletaPorId", WrapperNamespace="http://comprobantes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerBoletaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idBoleta;
        
        public obtenerBoletaPorIdRequest() {
        }
        
        public obtenerBoletaPorIdRequest(int idBoleta) {
            this.idBoleta = idBoleta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerBoletaPorIdResponse", WrapperNamespace="http://comprobantes.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerBoletaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprobantes.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.BoletaService.boleta @return;
        
        public obtenerBoletaPorIdResponse() {
        }
        
        public obtenerBoletaPorIdResponse(WearDropWA.BoletaService.boleta @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BoletaWSChannel : WearDropWA.BoletaService.BoletaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BoletaWSClient : System.ServiceModel.ClientBase<WearDropWA.BoletaService.BoletaWS>, WearDropWA.BoletaService.BoletaWS {
        
        public BoletaWSClient() {
        }
        
        public BoletaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BoletaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BoletaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BoletaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BoletaService.eliminarBoletaResponse WearDropWA.BoletaService.BoletaWS.eliminarBoleta(WearDropWA.BoletaService.eliminarBoletaRequest request) {
            return base.Channel.eliminarBoleta(request);
        }
        
        public int eliminarBoleta(int idBoleta) {
            WearDropWA.BoletaService.eliminarBoletaRequest inValue = new WearDropWA.BoletaService.eliminarBoletaRequest();
            inValue.idBoleta = idBoleta;
            WearDropWA.BoletaService.eliminarBoletaResponse retVal = ((WearDropWA.BoletaService.BoletaWS)(this)).eliminarBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BoletaService.eliminarBoletaResponse> WearDropWA.BoletaService.BoletaWS.eliminarBoletaAsync(WearDropWA.BoletaService.eliminarBoletaRequest request) {
            return base.Channel.eliminarBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BoletaService.eliminarBoletaResponse> eliminarBoletaAsync(int idBoleta) {
            WearDropWA.BoletaService.eliminarBoletaRequest inValue = new WearDropWA.BoletaService.eliminarBoletaRequest();
            inValue.idBoleta = idBoleta;
            return ((WearDropWA.BoletaService.BoletaWS)(this)).eliminarBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BoletaService.modificarBoletaResponse WearDropWA.BoletaService.BoletaWS.modificarBoleta(WearDropWA.BoletaService.modificarBoletaRequest request) {
            return base.Channel.modificarBoleta(request);
        }
        
        public int modificarBoleta(WearDropWA.BoletaService.boleta datBoleta) {
            WearDropWA.BoletaService.modificarBoletaRequest inValue = new WearDropWA.BoletaService.modificarBoletaRequest();
            inValue.datBoleta = datBoleta;
            WearDropWA.BoletaService.modificarBoletaResponse retVal = ((WearDropWA.BoletaService.BoletaWS)(this)).modificarBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BoletaService.modificarBoletaResponse> WearDropWA.BoletaService.BoletaWS.modificarBoletaAsync(WearDropWA.BoletaService.modificarBoletaRequest request) {
            return base.Channel.modificarBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BoletaService.modificarBoletaResponse> modificarBoletaAsync(WearDropWA.BoletaService.boleta datBoleta) {
            WearDropWA.BoletaService.modificarBoletaRequest inValue = new WearDropWA.BoletaService.modificarBoletaRequest();
            inValue.datBoleta = datBoleta;
            return ((WearDropWA.BoletaService.BoletaWS)(this)).modificarBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BoletaService.listarTodasBoletasResponse WearDropWA.BoletaService.BoletaWS.listarTodasBoletas(WearDropWA.BoletaService.listarTodasBoletasRequest request) {
            return base.Channel.listarTodasBoletas(request);
        }
        
        public WearDropWA.BoletaService.boleta[] listarTodasBoletas() {
            WearDropWA.BoletaService.listarTodasBoletasRequest inValue = new WearDropWA.BoletaService.listarTodasBoletasRequest();
            WearDropWA.BoletaService.listarTodasBoletasResponse retVal = ((WearDropWA.BoletaService.BoletaWS)(this)).listarTodasBoletas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BoletaService.listarTodasBoletasResponse> WearDropWA.BoletaService.BoletaWS.listarTodasBoletasAsync(WearDropWA.BoletaService.listarTodasBoletasRequest request) {
            return base.Channel.listarTodasBoletasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BoletaService.listarTodasBoletasResponse> listarTodasBoletasAsync() {
            WearDropWA.BoletaService.listarTodasBoletasRequest inValue = new WearDropWA.BoletaService.listarTodasBoletasRequest();
            return ((WearDropWA.BoletaService.BoletaWS)(this)).listarTodasBoletasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BoletaService.insertarBoletaResponse WearDropWA.BoletaService.BoletaWS.insertarBoleta(WearDropWA.BoletaService.insertarBoletaRequest request) {
            return base.Channel.insertarBoleta(request);
        }
        
        public int insertarBoleta(WearDropWA.BoletaService.boleta datBoleta) {
            WearDropWA.BoletaService.insertarBoletaRequest inValue = new WearDropWA.BoletaService.insertarBoletaRequest();
            inValue.datBoleta = datBoleta;
            WearDropWA.BoletaService.insertarBoletaResponse retVal = ((WearDropWA.BoletaService.BoletaWS)(this)).insertarBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BoletaService.insertarBoletaResponse> WearDropWA.BoletaService.BoletaWS.insertarBoletaAsync(WearDropWA.BoletaService.insertarBoletaRequest request) {
            return base.Channel.insertarBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BoletaService.insertarBoletaResponse> insertarBoletaAsync(WearDropWA.BoletaService.boleta datBoleta) {
            WearDropWA.BoletaService.insertarBoletaRequest inValue = new WearDropWA.BoletaService.insertarBoletaRequest();
            inValue.datBoleta = datBoleta;
            return ((WearDropWA.BoletaService.BoletaWS)(this)).insertarBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BoletaService.obtenerBoletaPorIdResponse WearDropWA.BoletaService.BoletaWS.obtenerBoletaPorId(WearDropWA.BoletaService.obtenerBoletaPorIdRequest request) {
            return base.Channel.obtenerBoletaPorId(request);
        }
        
        public WearDropWA.BoletaService.boleta obtenerBoletaPorId(int idBoleta) {
            WearDropWA.BoletaService.obtenerBoletaPorIdRequest inValue = new WearDropWA.BoletaService.obtenerBoletaPorIdRequest();
            inValue.idBoleta = idBoleta;
            WearDropWA.BoletaService.obtenerBoletaPorIdResponse retVal = ((WearDropWA.BoletaService.BoletaWS)(this)).obtenerBoletaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BoletaService.obtenerBoletaPorIdResponse> WearDropWA.BoletaService.BoletaWS.obtenerBoletaPorIdAsync(WearDropWA.BoletaService.obtenerBoletaPorIdRequest request) {
            return base.Channel.obtenerBoletaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BoletaService.obtenerBoletaPorIdResponse> obtenerBoletaPorIdAsync(int idBoleta) {
            WearDropWA.BoletaService.obtenerBoletaPorIdRequest inValue = new WearDropWA.BoletaService.obtenerBoletaPorIdRequest();
            inValue.idBoleta = idBoleta;
            return ((WearDropWA.BoletaService.BoletaWS)(this)).obtenerBoletaPorIdAsync(inValue);
        }
    }
}
