//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.OrdenCompraWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/", ConfigurationName="OrdenCompraWS.OrdenCompraWS")]
    public interface OrdenCompraWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/listarTodasLasOr" +
            "denesDeCompraRequest", ReplyAction="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/listarTodasLasOr" +
            "denesDeCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraResponse listarTodasLasOrdenesDeCompra(WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/listarTodasLasOr" +
            "denesDeCompraRequest", ReplyAction="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/listarTodasLasOr" +
            "denesDeCompraResponse")]
        System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraResponse> listarTodasLasOrdenesDeCompraAsync(WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/modificarOrdeneD" +
            "eCompraRequest", ReplyAction="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/modificarOrdeneD" +
            "eCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraResponse modificarOrdeneDeCompra(WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/modificarOrdeneD" +
            "eCompraRequest", ReplyAction="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/modificarOrdeneD" +
            "eCompraResponse")]
        System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraResponse> modificarOrdeneDeCompraAsync(WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/obtenerOrdenDeCo" +
            "mpraPorIDRequest", ReplyAction="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/obtenerOrdenDeCo" +
            "mpraPorIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDResponse obtenerOrdenDeCompraPorID(WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/obtenerOrdenDeCo" +
            "mpraPorIDRequest", ReplyAction="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/obtenerOrdenDeCo" +
            "mpraPorIDResponse")]
        System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDResponse> obtenerOrdenDeCompraPorIDAsync(WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/eliminarOrdenDeC" +
            "ompraRequest", ReplyAction="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/eliminarOrdenDeC" +
            "ompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraResponse eliminarOrdenDeCompra(WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/eliminarOrdenDeC" +
            "ompraRequest", ReplyAction="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/eliminarOrdenDeC" +
            "ompraResponse")]
        System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraResponse> eliminarOrdenDeCompraAsync(WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/insertarOrdenDeC" +
            "ompraRequest", ReplyAction="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/insertarOrdenDeC" +
            "ompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.OrdenCompraWS.insertarOrdenDeCompraResponse insertarOrdenDeCompra(WearDropWA.OrdenCompraWS.insertarOrdenDeCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/insertarOrdenDeC" +
            "ompraRequest", ReplyAction="http://comprastienda.services.weardrop.pucp.edu.pe/OrdenCompraWS/insertarOrdenDeC" +
            "ompraResponse")]
        System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.insertarOrdenDeCompraResponse> insertarOrdenDeCompraAsync(WearDropWA.OrdenCompraWS.insertarOrdenDeCompraRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/")]
    public partial class ordenCompra : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private double deudaPendienteField;
        
        private empleado empleadoField;
        
        private System.DateTime fechaEmisionField;
        
        private bool fechaEmisionFieldSpecified;
        
        private System.DateTime fechaLlegadaField;
        
        private bool fechaLlegadaFieldSpecified;
        
        private int idCompraField;
        
        private lineaLoteCompra[] itemsField;
        
        private double montoTotalField;
        
        private proveedor proveedorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double deudaPendiente {
            get {
                return this.deudaPendienteField;
            }
            set {
                this.deudaPendienteField = value;
                this.RaisePropertyChanged("deudaPendiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("empleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionSpecified {
            get {
                return this.fechaEmisionFieldSpecified;
            }
            set {
                this.fechaEmisionFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaLlegada {
            get {
                return this.fechaLlegadaField;
            }
            set {
                this.fechaLlegadaField = value;
                this.RaisePropertyChanged("fechaLlegada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaLlegadaSpecified {
            get {
                return this.fechaLlegadaFieldSpecified;
            }
            set {
                this.fechaLlegadaFieldSpecified = value;
                this.RaisePropertyChanged("fechaLlegadaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idCompra {
            get {
                return this.idCompraField;
            }
            set {
                this.idCompraField = value;
                this.RaisePropertyChanged("idCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public lineaLoteCompra[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double montoTotal {
            get {
                return this.montoTotalField;
            }
            set {
                this.montoTotalField = value;
                this.RaisePropertyChanged("montoTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public proveedor proveedor {
            get {
                return this.proveedorField;
            }
            set {
                this.proveedorField = value;
                this.RaisePropertyChanged("proveedor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/")]
    public partial class empleado : persona {
        
        private bool activoField;
        
        private cargo cargoAsignadoField;
        
        private int idEmpleadoField;
        
        private double sueldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cargo cargoAsignado {
            get {
                return this.cargoAsignadoField;
            }
            set {
                this.cargoAsignadoField = value;
                this.RaisePropertyChanged("cargoAsignado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                this.idEmpleadoField = value;
                this.RaisePropertyChanged("idEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double sueldo {
            get {
                return this.sueldoField;
            }
            set {
                this.sueldoField = value;
                this.RaisePropertyChanged("sueldo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/")]
    public partial class cargo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort abreviaturaField;
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idCargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
                this.RaisePropertyChanged("abreviatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCargo {
            get {
                return this.idCargoField;
            }
            set {
                this.idCargoField = value;
                this.RaisePropertyChanged("idCargo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/")]
    public partial class condicionPago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idCondicionField;
        
        private int numDiasField;
        
        private bool vigenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCondicion {
            get {
                return this.idCondicionField;
            }
            set {
                this.idCondicionField = value;
                this.RaisePropertyChanged("idCondicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numDias {
            get {
                return this.numDiasField;
            }
            set {
                this.numDiasField = value;
                this.RaisePropertyChanged("numDias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool vigente {
            get {
                return this.vigenteField;
            }
            set {
                this.vigenteField = value;
                this.RaisePropertyChanged("vigente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/")]
    public partial class proveedor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private condicionPago[] condicionesField;
        
        private string direccionField;
        
        private int idProveedorField;
        
        private string nombreField;
        
        private long rUCField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("condiciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public condicionPago[] condiciones {
            get {
                return this.condicionesField;
            }
            set {
                this.condicionesField = value;
                this.RaisePropertyChanged("condiciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProveedor {
            get {
                return this.idProveedorField;
            }
            set {
                this.idProveedorField = value;
                this.RaisePropertyChanged("idProveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long RUC {
            get {
                return this.rUCField;
            }
            set {
                this.rUCField = value;
                this.RaisePropertyChanged("RUC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/")]
    public partial class almacen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idField;
        
        private int idTiendaField;
        
        private string nombreField;
        
        private int stockField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTienda {
            get {
                return this.idTiendaField;
            }
            set {
                this.idTiendaField = value;
                this.RaisePropertyChanged("idTienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/")]
    public partial class lote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private almacen datAlmacenField;
        
        private string descripcionField;
        
        private int idLoteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public almacen datAlmacen {
            get {
                return this.datAlmacenField;
            }
            set {
                this.datAlmacenField = value;
                this.RaisePropertyChanged("datAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idLote {
            get {
                return this.idLoteField;
            }
            set {
                this.idLoteField = value;
                this.RaisePropertyChanged("idLote");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/")]
    public partial class lineaLoteCompra : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int cantidadField;
        
        private int idPrendaField;
        
        private lote loteField;
        
        private int numLineaField;
        
        private double precioLoteField;
        
        private talla tallaField;
        
        private bool tallaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPrenda {
            get {
                return this.idPrendaField;
            }
            set {
                this.idPrendaField = value;
                this.RaisePropertyChanged("idPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public lote lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numLinea {
            get {
                return this.numLineaField;
            }
            set {
                this.numLineaField = value;
                this.RaisePropertyChanged("numLinea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precioLote {
            get {
                return this.precioLoteField;
            }
            set {
                this.precioLoteField = value;
                this.RaisePropertyChanged("precioLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public talla talla {
            get {
                return this.tallaField;
            }
            set {
                this.tallaField = value;
                this.RaisePropertyChanged("talla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tallaSpecified {
            get {
                return this.tallaFieldSpecified;
            }
            set {
                this.tallaFieldSpecified = value;
                this.RaisePropertyChanged("tallaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/")]
    public enum talla {
        
        /// <remarks/>
        XS,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        XL,
        
        /// <remarks/>
        XXL,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dniField;
        
        private ushort generoField;
        
        private int idPersonaField;
        
        private string nombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasLasOrdenesDeCompra", WrapperNamespace="http://comprastienda.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasLasOrdenesDeCompraRequest {
        
        public listarTodasLasOrdenesDeCompraRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasLasOrdenesDeCompraResponse", WrapperNamespace="http://comprastienda.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasLasOrdenesDeCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.OrdenCompraWS.ordenCompra[] @return;
        
        public listarTodasLasOrdenesDeCompraResponse() {
        }
        
        public listarTodasLasOrdenesDeCompraResponse(WearDropWA.OrdenCompraWS.ordenCompra[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarOrdeneDeCompra", WrapperNamespace="http://comprastienda.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarOrdeneDeCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.OrdenCompraWS.ordenCompra datOrdenCompra;
        
        public modificarOrdeneDeCompraRequest() {
        }
        
        public modificarOrdeneDeCompraRequest(WearDropWA.OrdenCompraWS.ordenCompra datOrdenCompra) {
            this.datOrdenCompra = datOrdenCompra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarOrdeneDeCompraResponse", WrapperNamespace="http://comprastienda.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarOrdeneDeCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarOrdeneDeCompraResponse() {
        }
        
        public modificarOrdeneDeCompraResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerOrdenDeCompraPorID", WrapperNamespace="http://comprastienda.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerOrdenDeCompraPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOrdenCompra;
        
        public obtenerOrdenDeCompraPorIDRequest() {
        }
        
        public obtenerOrdenDeCompraPorIDRequest(int idOrdenCompra) {
            this.idOrdenCompra = idOrdenCompra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerOrdenDeCompraPorIDResponse", WrapperNamespace="http://comprastienda.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerOrdenDeCompraPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.OrdenCompraWS.ordenCompra @return;
        
        public obtenerOrdenDeCompraPorIDResponse() {
        }
        
        public obtenerOrdenDeCompraPorIDResponse(WearDropWA.OrdenCompraWS.ordenCompra @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenDeCompra", WrapperNamespace="http://comprastienda.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOrdenDeCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOrdenCompra;
        
        public eliminarOrdenDeCompraRequest() {
        }
        
        public eliminarOrdenDeCompraRequest(int idOrdenCompra) {
            this.idOrdenCompra = idOrdenCompra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenDeCompraResponse", WrapperNamespace="http://comprastienda.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOrdenDeCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarOrdenDeCompraResponse() {
        }
        
        public eliminarOrdenDeCompraResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenDeCompra", WrapperNamespace="http://comprastienda.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOrdenDeCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.OrdenCompraWS.ordenCompra datOrdenCompra;
        
        public insertarOrdenDeCompraRequest() {
        }
        
        public insertarOrdenDeCompraRequest(WearDropWA.OrdenCompraWS.ordenCompra datOrdenCompra) {
            this.datOrdenCompra = datOrdenCompra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenDeCompraResponse", WrapperNamespace="http://comprastienda.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOrdenDeCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://comprastienda.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarOrdenDeCompraResponse() {
        }
        
        public insertarOrdenDeCompraResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenCompraWSChannel : WearDropWA.OrdenCompraWS.OrdenCompraWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenCompraWSClient : System.ServiceModel.ClientBase<WearDropWA.OrdenCompraWS.OrdenCompraWS>, WearDropWA.OrdenCompraWS.OrdenCompraWS {
        
        public OrdenCompraWSClient() {
        }
        
        public OrdenCompraWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenCompraWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenCompraWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenCompraWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraResponse WearDropWA.OrdenCompraWS.OrdenCompraWS.listarTodasLasOrdenesDeCompra(WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraRequest request) {
            return base.Channel.listarTodasLasOrdenesDeCompra(request);
        }
        
        public WearDropWA.OrdenCompraWS.ordenCompra[] listarTodasLasOrdenesDeCompra() {
            WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraRequest inValue = new WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraRequest();
            WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraResponse retVal = ((WearDropWA.OrdenCompraWS.OrdenCompraWS)(this)).listarTodasLasOrdenesDeCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraResponse> WearDropWA.OrdenCompraWS.OrdenCompraWS.listarTodasLasOrdenesDeCompraAsync(WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraRequest request) {
            return base.Channel.listarTodasLasOrdenesDeCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraResponse> listarTodasLasOrdenesDeCompraAsync() {
            WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraRequest inValue = new WearDropWA.OrdenCompraWS.listarTodasLasOrdenesDeCompraRequest();
            return ((WearDropWA.OrdenCompraWS.OrdenCompraWS)(this)).listarTodasLasOrdenesDeCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraResponse WearDropWA.OrdenCompraWS.OrdenCompraWS.modificarOrdeneDeCompra(WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraRequest request) {
            return base.Channel.modificarOrdeneDeCompra(request);
        }
        
        public int modificarOrdeneDeCompra(WearDropWA.OrdenCompraWS.ordenCompra datOrdenCompra) {
            WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraRequest inValue = new WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraRequest();
            inValue.datOrdenCompra = datOrdenCompra;
            WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraResponse retVal = ((WearDropWA.OrdenCompraWS.OrdenCompraWS)(this)).modificarOrdeneDeCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraResponse> WearDropWA.OrdenCompraWS.OrdenCompraWS.modificarOrdeneDeCompraAsync(WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraRequest request) {
            return base.Channel.modificarOrdeneDeCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraResponse> modificarOrdeneDeCompraAsync(WearDropWA.OrdenCompraWS.ordenCompra datOrdenCompra) {
            WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraRequest inValue = new WearDropWA.OrdenCompraWS.modificarOrdeneDeCompraRequest();
            inValue.datOrdenCompra = datOrdenCompra;
            return ((WearDropWA.OrdenCompraWS.OrdenCompraWS)(this)).modificarOrdeneDeCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDResponse WearDropWA.OrdenCompraWS.OrdenCompraWS.obtenerOrdenDeCompraPorID(WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDRequest request) {
            return base.Channel.obtenerOrdenDeCompraPorID(request);
        }
        
        public WearDropWA.OrdenCompraWS.ordenCompra obtenerOrdenDeCompraPorID(int idOrdenCompra) {
            WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDRequest inValue = new WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDRequest();
            inValue.idOrdenCompra = idOrdenCompra;
            WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDResponse retVal = ((WearDropWA.OrdenCompraWS.OrdenCompraWS)(this)).obtenerOrdenDeCompraPorID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDResponse> WearDropWA.OrdenCompraWS.OrdenCompraWS.obtenerOrdenDeCompraPorIDAsync(WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDRequest request) {
            return base.Channel.obtenerOrdenDeCompraPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDResponse> obtenerOrdenDeCompraPorIDAsync(int idOrdenCompra) {
            WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDRequest inValue = new WearDropWA.OrdenCompraWS.obtenerOrdenDeCompraPorIDRequest();
            inValue.idOrdenCompra = idOrdenCompra;
            return ((WearDropWA.OrdenCompraWS.OrdenCompraWS)(this)).obtenerOrdenDeCompraPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraResponse WearDropWA.OrdenCompraWS.OrdenCompraWS.eliminarOrdenDeCompra(WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraRequest request) {
            return base.Channel.eliminarOrdenDeCompra(request);
        }
        
        public int eliminarOrdenDeCompra(int idOrdenCompra) {
            WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraRequest inValue = new WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraRequest();
            inValue.idOrdenCompra = idOrdenCompra;
            WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraResponse retVal = ((WearDropWA.OrdenCompraWS.OrdenCompraWS)(this)).eliminarOrdenDeCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraResponse> WearDropWA.OrdenCompraWS.OrdenCompraWS.eliminarOrdenDeCompraAsync(WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraRequest request) {
            return base.Channel.eliminarOrdenDeCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraResponse> eliminarOrdenDeCompraAsync(int idOrdenCompra) {
            WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraRequest inValue = new WearDropWA.OrdenCompraWS.eliminarOrdenDeCompraRequest();
            inValue.idOrdenCompra = idOrdenCompra;
            return ((WearDropWA.OrdenCompraWS.OrdenCompraWS)(this)).eliminarOrdenDeCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.OrdenCompraWS.insertarOrdenDeCompraResponse WearDropWA.OrdenCompraWS.OrdenCompraWS.insertarOrdenDeCompra(WearDropWA.OrdenCompraWS.insertarOrdenDeCompraRequest request) {
            return base.Channel.insertarOrdenDeCompra(request);
        }
        
        public int insertarOrdenDeCompra(WearDropWA.OrdenCompraWS.ordenCompra datOrdenCompra) {
            WearDropWA.OrdenCompraWS.insertarOrdenDeCompraRequest inValue = new WearDropWA.OrdenCompraWS.insertarOrdenDeCompraRequest();
            inValue.datOrdenCompra = datOrdenCompra;
            WearDropWA.OrdenCompraWS.insertarOrdenDeCompraResponse retVal = ((WearDropWA.OrdenCompraWS.OrdenCompraWS)(this)).insertarOrdenDeCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.insertarOrdenDeCompraResponse> WearDropWA.OrdenCompraWS.OrdenCompraWS.insertarOrdenDeCompraAsync(WearDropWA.OrdenCompraWS.insertarOrdenDeCompraRequest request) {
            return base.Channel.insertarOrdenDeCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.OrdenCompraWS.insertarOrdenDeCompraResponse> insertarOrdenDeCompraAsync(WearDropWA.OrdenCompraWS.ordenCompra datOrdenCompra) {
            WearDropWA.OrdenCompraWS.insertarOrdenDeCompraRequest inValue = new WearDropWA.OrdenCompraWS.insertarOrdenDeCompraRequest();
            inValue.datOrdenCompra = datOrdenCompra;
            return ((WearDropWA.OrdenCompraWS.OrdenCompraWS)(this)).insertarOrdenDeCompraAsync(inValue);
        }
    }
}
