//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.ReporteVentaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="pe.edu.pucp.weardrop.services", ConfigurationName="ReporteVentaWS.ReporteVentaWS")]
    public interface ReporteVentaWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pFechaDesde del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.weardrop.services/ReporteVentaWS/generarReporteVentasPorPrendaRequest" +
            "", ReplyAction="pe.edu.pucp.weardrop.services/ReporteVentaWS/generarReporteVentasPorPrendaRespons" +
            "e")]
        WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaResponse generarReporteVentasPorPrenda(WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.weardrop.services/ReporteVentaWS/generarReporteVentasPorPrendaRequest" +
            "", ReplyAction="pe.edu.pucp.weardrop.services/ReporteVentaWS/generarReporteVentasPorPrendaRespons" +
            "e")]
        System.Threading.Tasks.Task<WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaResponse> generarReporteVentasPorPrendaAsync(WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReporteVentasPorPrendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReporteVentasPorPrenda", Namespace="pe.edu.pucp.weardrop.services", Order=0)]
        public WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequestBody Body;
        
        public generarReporteVentasPorPrendaRequest() {
        }
        
        public generarReporteVentasPorPrendaRequest(WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReporteVentasPorPrendaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pFechaDesde;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pFechaHasta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipoPeriodo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Empleado;
        
        public generarReporteVentasPorPrendaRequestBody() {
        }
        
        public generarReporteVentasPorPrendaRequestBody(string pFechaDesde, string pFechaHasta, string tipoPeriodo, string Empleado) {
            this.pFechaDesde = pFechaDesde;
            this.pFechaHasta = pFechaHasta;
            this.tipoPeriodo = tipoPeriodo;
            this.Empleado = Empleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReporteVentasPorPrendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReporteVentasPorPrendaResponse", Namespace="pe.edu.pucp.weardrop.services", Order=0)]
        public WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaResponseBody Body;
        
        public generarReporteVentasPorPrendaResponse() {
        }
        
        public generarReporteVentasPorPrendaResponse(WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReporteVentasPorPrendaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public generarReporteVentasPorPrendaResponseBody() {
        }
        
        public generarReporteVentasPorPrendaResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteVentaWSChannel : WearDropWA.ReporteVentaWS.ReporteVentaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteVentaWSClient : System.ServiceModel.ClientBase<WearDropWA.ReporteVentaWS.ReporteVentaWS>, WearDropWA.ReporteVentaWS.ReporteVentaWS {
        
        public ReporteVentaWSClient() {
        }
        
        public ReporteVentaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteVentaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteVentaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteVentaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaResponse WearDropWA.ReporteVentaWS.ReporteVentaWS.generarReporteVentasPorPrenda(WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequest request) {
            return base.Channel.generarReporteVentasPorPrenda(request);
        }
        
        public byte[] generarReporteVentasPorPrenda(string pFechaDesde, string pFechaHasta, string tipoPeriodo, string Empleado) {
            WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequest inValue = new WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequest();
            inValue.Body = new WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequestBody();
            inValue.Body.pFechaDesde = pFechaDesde;
            inValue.Body.pFechaHasta = pFechaHasta;
            inValue.Body.tipoPeriodo = tipoPeriodo;
            inValue.Body.Empleado = Empleado;
            WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaResponse retVal = ((WearDropWA.ReporteVentaWS.ReporteVentaWS)(this)).generarReporteVentasPorPrenda(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaResponse> WearDropWA.ReporteVentaWS.ReporteVentaWS.generarReporteVentasPorPrendaAsync(WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequest request) {
            return base.Channel.generarReporteVentasPorPrendaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaResponse> generarReporteVentasPorPrendaAsync(string pFechaDesde, string pFechaHasta, string tipoPeriodo, string Empleado) {
            WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequest inValue = new WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequest();
            inValue.Body = new WearDropWA.ReporteVentaWS.generarReporteVentasPorPrendaRequestBody();
            inValue.Body.pFechaDesde = pFechaDesde;
            inValue.Body.pFechaHasta = pFechaHasta;
            inValue.Body.tipoPeriodo = tipoPeriodo;
            inValue.Body.Empleado = Empleado;
            return ((WearDropWA.ReporteVentaWS.ReporteVentaWS)(this)).generarReporteVentasPorPrendaAsync(inValue);
        }
    }
}
