//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.CargoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", ConfigurationName="CargoWS.CargoWS")]
    public interface CargoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CargoWS/listarCargosRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CargoWS/listarCargosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CargoWS.listarCargosResponse listarCargos(WearDropWA.CargoWS.listarCargosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CargoWS/listarCargosRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CargoWS/listarCargosResponse")]
        System.Threading.Tasks.Task<WearDropWA.CargoWS.listarCargosResponse> listarCargosAsync(WearDropWA.CargoWS.listarCargosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CargoWS/obtenerCargoPorIdRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CargoWS/obtenerCargoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CargoWS.obtenerCargoPorIdResponse obtenerCargoPorId(WearDropWA.CargoWS.obtenerCargoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CargoWS/obtenerCargoPorIdRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CargoWS/obtenerCargoPorIdResponse")]
        System.Threading.Tasks.Task<WearDropWA.CargoWS.obtenerCargoPorIdResponse> obtenerCargoPorIdAsync(WearDropWA.CargoWS.obtenerCargoPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CargoWS/insertarCargoRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CargoWS/insertarCargoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CargoWS.insertarCargoResponse insertarCargo(WearDropWA.CargoWS.insertarCargoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CargoWS/insertarCargoRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CargoWS/insertarCargoResponse")]
        System.Threading.Tasks.Task<WearDropWA.CargoWS.insertarCargoResponse> insertarCargoAsync(WearDropWA.CargoWS.insertarCargoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CargoWS/modificarCargoRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CargoWS/modificarCargoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CargoWS.modificarCargoResponse modificarCargo(WearDropWA.CargoWS.modificarCargoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CargoWS/modificarCargoRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CargoWS/modificarCargoResponse")]
        System.Threading.Tasks.Task<WearDropWA.CargoWS.modificarCargoResponse> modificarCargoAsync(WearDropWA.CargoWS.modificarCargoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CargoWS/eliminarCargoRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CargoWS/eliminarCargoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CargoWS.eliminarCargoResponse eliminarCargo(WearDropWA.CargoWS.eliminarCargoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CargoWS/eliminarCargoRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CargoWS/eliminarCargoResponse")]
        System.Threading.Tasks.Task<WearDropWA.CargoWS.eliminarCargoResponse> eliminarCargoAsync(WearDropWA.CargoWS.eliminarCargoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/")]
    public partial class cargo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort abreviaturaField;
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idCargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
                this.RaisePropertyChanged("abreviatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCargo {
            get {
                return this.idCargoField;
            }
            set {
                this.idCargoField = value;
                this.RaisePropertyChanged("idCargo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCargos", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCargosRequest {
        
        public listarCargosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCargosResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCargosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CargoWS.cargo[] @return;
        
        public listarCargosResponse() {
        }
        
        public listarCargosResponse(WearDropWA.CargoWS.cargo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCargoPorId", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCargoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCargo;
        
        public obtenerCargoPorIdRequest() {
        }
        
        public obtenerCargoPorIdRequest(int idCargo) {
            this.idCargo = idCargo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCargoPorIdResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCargoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CargoWS.cargo @return;
        
        public obtenerCargoPorIdResponse() {
        }
        
        public obtenerCargoPorIdResponse(WearDropWA.CargoWS.cargo @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCargo", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCargoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CargoWS.cargo cargo;
        
        public insertarCargoRequest() {
        }
        
        public insertarCargoRequest(WearDropWA.CargoWS.cargo cargo) {
            this.cargo = cargo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCargoResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCargoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCargoResponse() {
        }
        
        public insertarCargoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCargo", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCargoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CargoWS.cargo cargo;
        
        public modificarCargoRequest() {
        }
        
        public modificarCargoRequest(WearDropWA.CargoWS.cargo cargo) {
            this.cargo = cargo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCargoResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCargoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCargoResponse() {
        }
        
        public modificarCargoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCargo", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCargoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCargo;
        
        public eliminarCargoRequest() {
        }
        
        public eliminarCargoRequest(int idCargo) {
            this.idCargo = idCargo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCargoResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCargoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCargoResponse() {
        }
        
        public eliminarCargoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CargoWSChannel : WearDropWA.CargoWS.CargoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CargoWSClient : System.ServiceModel.ClientBase<WearDropWA.CargoWS.CargoWS>, WearDropWA.CargoWS.CargoWS {
        
        public CargoWSClient() {
        }
        
        public CargoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CargoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CargoWS.listarCargosResponse WearDropWA.CargoWS.CargoWS.listarCargos(WearDropWA.CargoWS.listarCargosRequest request) {
            return base.Channel.listarCargos(request);
        }
        
        public WearDropWA.CargoWS.cargo[] listarCargos() {
            WearDropWA.CargoWS.listarCargosRequest inValue = new WearDropWA.CargoWS.listarCargosRequest();
            WearDropWA.CargoWS.listarCargosResponse retVal = ((WearDropWA.CargoWS.CargoWS)(this)).listarCargos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CargoWS.listarCargosResponse> WearDropWA.CargoWS.CargoWS.listarCargosAsync(WearDropWA.CargoWS.listarCargosRequest request) {
            return base.Channel.listarCargosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CargoWS.listarCargosResponse> listarCargosAsync() {
            WearDropWA.CargoWS.listarCargosRequest inValue = new WearDropWA.CargoWS.listarCargosRequest();
            return ((WearDropWA.CargoWS.CargoWS)(this)).listarCargosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CargoWS.obtenerCargoPorIdResponse WearDropWA.CargoWS.CargoWS.obtenerCargoPorId(WearDropWA.CargoWS.obtenerCargoPorIdRequest request) {
            return base.Channel.obtenerCargoPorId(request);
        }
        
        public WearDropWA.CargoWS.cargo obtenerCargoPorId(int idCargo) {
            WearDropWA.CargoWS.obtenerCargoPorIdRequest inValue = new WearDropWA.CargoWS.obtenerCargoPorIdRequest();
            inValue.idCargo = idCargo;
            WearDropWA.CargoWS.obtenerCargoPorIdResponse retVal = ((WearDropWA.CargoWS.CargoWS)(this)).obtenerCargoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CargoWS.obtenerCargoPorIdResponse> WearDropWA.CargoWS.CargoWS.obtenerCargoPorIdAsync(WearDropWA.CargoWS.obtenerCargoPorIdRequest request) {
            return base.Channel.obtenerCargoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CargoWS.obtenerCargoPorIdResponse> obtenerCargoPorIdAsync(int idCargo) {
            WearDropWA.CargoWS.obtenerCargoPorIdRequest inValue = new WearDropWA.CargoWS.obtenerCargoPorIdRequest();
            inValue.idCargo = idCargo;
            return ((WearDropWA.CargoWS.CargoWS)(this)).obtenerCargoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CargoWS.insertarCargoResponse WearDropWA.CargoWS.CargoWS.insertarCargo(WearDropWA.CargoWS.insertarCargoRequest request) {
            return base.Channel.insertarCargo(request);
        }
        
        public int insertarCargo(WearDropWA.CargoWS.cargo cargo) {
            WearDropWA.CargoWS.insertarCargoRequest inValue = new WearDropWA.CargoWS.insertarCargoRequest();
            inValue.cargo = cargo;
            WearDropWA.CargoWS.insertarCargoResponse retVal = ((WearDropWA.CargoWS.CargoWS)(this)).insertarCargo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CargoWS.insertarCargoResponse> WearDropWA.CargoWS.CargoWS.insertarCargoAsync(WearDropWA.CargoWS.insertarCargoRequest request) {
            return base.Channel.insertarCargoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CargoWS.insertarCargoResponse> insertarCargoAsync(WearDropWA.CargoWS.cargo cargo) {
            WearDropWA.CargoWS.insertarCargoRequest inValue = new WearDropWA.CargoWS.insertarCargoRequest();
            inValue.cargo = cargo;
            return ((WearDropWA.CargoWS.CargoWS)(this)).insertarCargoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CargoWS.modificarCargoResponse WearDropWA.CargoWS.CargoWS.modificarCargo(WearDropWA.CargoWS.modificarCargoRequest request) {
            return base.Channel.modificarCargo(request);
        }
        
        public int modificarCargo(WearDropWA.CargoWS.cargo cargo) {
            WearDropWA.CargoWS.modificarCargoRequest inValue = new WearDropWA.CargoWS.modificarCargoRequest();
            inValue.cargo = cargo;
            WearDropWA.CargoWS.modificarCargoResponse retVal = ((WearDropWA.CargoWS.CargoWS)(this)).modificarCargo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CargoWS.modificarCargoResponse> WearDropWA.CargoWS.CargoWS.modificarCargoAsync(WearDropWA.CargoWS.modificarCargoRequest request) {
            return base.Channel.modificarCargoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CargoWS.modificarCargoResponse> modificarCargoAsync(WearDropWA.CargoWS.cargo cargo) {
            WearDropWA.CargoWS.modificarCargoRequest inValue = new WearDropWA.CargoWS.modificarCargoRequest();
            inValue.cargo = cargo;
            return ((WearDropWA.CargoWS.CargoWS)(this)).modificarCargoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CargoWS.eliminarCargoResponse WearDropWA.CargoWS.CargoWS.eliminarCargo(WearDropWA.CargoWS.eliminarCargoRequest request) {
            return base.Channel.eliminarCargo(request);
        }
        
        public int eliminarCargo(int idCargo) {
            WearDropWA.CargoWS.eliminarCargoRequest inValue = new WearDropWA.CargoWS.eliminarCargoRequest();
            inValue.idCargo = idCargo;
            WearDropWA.CargoWS.eliminarCargoResponse retVal = ((WearDropWA.CargoWS.CargoWS)(this)).eliminarCargo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CargoWS.eliminarCargoResponse> WearDropWA.CargoWS.CargoWS.eliminarCargoAsync(WearDropWA.CargoWS.eliminarCargoRequest request) {
            return base.Channel.eliminarCargoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CargoWS.eliminarCargoResponse> eliminarCargoAsync(int idCargo) {
            WearDropWA.CargoWS.eliminarCargoRequest inValue = new WearDropWA.CargoWS.eliminarCargoRequest();
            inValue.idCargo = idCargo;
            return ((WearDropWA.CargoWS.CargoWS)(this)).eliminarCargoAsync(inValue);
        }
    }
}
