//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.VentaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/", ConfigurationName="VentaWS.VentaWS")]
    public interface VentaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/eliminarVentaRequest", ReplyAction="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/eliminarVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VentaWS.eliminarVentaResponse eliminarVenta(WearDropWA.VentaWS.eliminarVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/eliminarVentaRequest", ReplyAction="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/eliminarVentaResponse")]
        System.Threading.Tasks.Task<WearDropWA.VentaWS.eliminarVentaResponse> eliminarVentaAsync(WearDropWA.VentaWS.eliminarVentaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/listarVentasRequest", ReplyAction="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/listarVentasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VentaWS.listarVentasResponse listarVentas(WearDropWA.VentaWS.listarVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/listarVentasRequest", ReplyAction="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/listarVentasResponse")]
        System.Threading.Tasks.Task<WearDropWA.VentaWS.listarVentasResponse> listarVentasAsync(WearDropWA.VentaWS.listarVentasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/obtenerVentaPorIdRequest", ReplyAction="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/obtenerVentaPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VentaWS.obtenerVentaPorIdResponse obtenerVentaPorId(WearDropWA.VentaWS.obtenerVentaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/obtenerVentaPorIdRequest", ReplyAction="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/obtenerVentaPorIdResponse")]
        System.Threading.Tasks.Task<WearDropWA.VentaWS.obtenerVentaPorIdResponse> obtenerVentaPorIdAsync(WearDropWA.VentaWS.obtenerVentaPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/modificarVentaRequest", ReplyAction="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/modificarVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VentaWS.modificarVentaResponse modificarVenta(WearDropWA.VentaWS.modificarVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/modificarVentaRequest", ReplyAction="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/modificarVentaResponse")]
        System.Threading.Tasks.Task<WearDropWA.VentaWS.modificarVentaResponse> modificarVentaAsync(WearDropWA.VentaWS.modificarVentaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/insertarVentaRequest", ReplyAction="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/insertarVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VentaWS.insertarVentaResponse insertarVenta(WearDropWA.VentaWS.insertarVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/insertarVentaRequest", ReplyAction="http://ventas.services.weardrop.pucp.edu.pe/VentaWS/insertarVentaResponse")]
        System.Threading.Tasks.Task<WearDropWA.VentaWS.insertarVentaResponse> insertarVentaAsync(WearDropWA.VentaWS.insertarVentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarVenta", WrapperNamespace="http://ventas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idVenta;
        
        public eliminarVentaRequest() {
        }
        
        public eliminarVentaRequest(int idVenta) {
            this.idVenta = idVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarVentaResponse", WrapperNamespace="http://ventas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarVentaResponse() {
        }
        
        public eliminarVentaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public partial class venta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private cliente clienteField;
        
        private empleado empleadoField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idComprobanteField;
        
        private int idVentaField;
        
        private itemVenta[] productosField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("empleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idComprobante {
            get {
                return this.idComprobanteField;
            }
            set {
                this.idComprobanteField = value;
                this.RaisePropertyChanged("idComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idVenta {
            get {
                return this.idVentaField;
            }
            set {
                this.idVentaField = value;
                this.RaisePropertyChanged("idVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public itemVenta[] productos {
            get {
                return this.productosField;
            }
            set {
                this.productosField = value;
                this.RaisePropertyChanged("productos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public partial class cliente : persona {
        
        private bool activoField;
        
        private venta[] historialComprasField;
        
        private int idClienteField;
        
        private tipoDeCliente tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("historialCompras", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public venta[] historialCompras {
            get {
                return this.historialComprasField;
            }
            set {
                this.historialComprasField = value;
                this.RaisePropertyChanged("historialCompras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tipoDeCliente tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public partial class tipoDeCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort abreviaturaField;
        
        private string descripcionField;
        
        private int tipoClienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
                this.RaisePropertyChanged("abreviatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int tipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("tipoCliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class promocion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idPromocionField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPromocion {
            get {
                return this.idPromocionField;
            }
            set {
                this.idPromocionField = value;
                this.RaisePropertyChanged("idPromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public partial class vigencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idVigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idVigencia {
            get {
                return this.idVigenciaField;
            }
            set {
                this.idVigenciaField = value;
                this.RaisePropertyChanged("idVigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class descuento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idDescuentoField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDescuento {
            get {
                return this.idDescuentoField;
            }
            set {
                this.idDescuentoField = value;
                this.RaisePropertyChanged("idDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public partial class itemVenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int cantidadField;
        
        private descuento[] descuentosField;
        
        private int idPrendaField;
        
        private int numLineaField;
        
        private promocion[] promocionesField;
        
        private double subtotalField;
        
        private talla tallaField;
        
        private bool tallaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descuentos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public descuento[] descuentos {
            get {
                return this.descuentosField;
            }
            set {
                this.descuentosField = value;
                this.RaisePropertyChanged("descuentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPrenda {
            get {
                return this.idPrendaField;
            }
            set {
                this.idPrendaField = value;
                this.RaisePropertyChanged("idPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numLinea {
            get {
                return this.numLineaField;
            }
            set {
                this.numLineaField = value;
                this.RaisePropertyChanged("numLinea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("promociones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public promocion[] promociones {
            get {
                return this.promocionesField;
            }
            set {
                this.promocionesField = value;
                this.RaisePropertyChanged("promociones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public talla talla {
            get {
                return this.tallaField;
            }
            set {
                this.tallaField = value;
                this.RaisePropertyChanged("talla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tallaSpecified {
            get {
                return this.tallaFieldSpecified;
            }
            set {
                this.tallaFieldSpecified = value;
                this.RaisePropertyChanged("tallaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public enum talla {
        
        /// <remarks/>
        XS,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        XL,
        
        /// <remarks/>
        XXL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public partial class cargo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort abreviaturaField;
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idCargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
                this.RaisePropertyChanged("abreviatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCargo {
            get {
                return this.idCargoField;
            }
            set {
                this.idCargoField = value;
                this.RaisePropertyChanged("idCargo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dniField;
        
        private ushort generoField;
        
        private int idPersonaField;
        
        private string nombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/")]
    public partial class empleado : persona {
        
        private bool activoField;
        
        private cargo cargoAsignadoField;
        
        private int idEmpleadoField;
        
        private double sueldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cargo cargoAsignado {
            get {
                return this.cargoAsignadoField;
            }
            set {
                this.cargoAsignadoField = value;
                this.RaisePropertyChanged("cargoAsignado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                this.idEmpleadoField = value;
                this.RaisePropertyChanged("idEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double sueldo {
            get {
                return this.sueldoField;
            }
            set {
                this.sueldoField = value;
                this.RaisePropertyChanged("sueldo");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVentas", WrapperNamespace="http://ventas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarVentasRequest {
        
        public listarVentasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVentasResponse", WrapperNamespace="http://ventas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.VentaWS.venta[] @return;
        
        public listarVentasResponse() {
        }
        
        public listarVentasResponse(WearDropWA.VentaWS.venta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerVentaPorId", WrapperNamespace="http://ventas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerVentaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idVenta;
        
        public obtenerVentaPorIdRequest() {
        }
        
        public obtenerVentaPorIdRequest(int idVenta) {
            this.idVenta = idVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerVentaPorIdResponse", WrapperNamespace="http://ventas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerVentaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.VentaWS.venta @return;
        
        public obtenerVentaPorIdResponse() {
        }
        
        public obtenerVentaPorIdResponse(WearDropWA.VentaWS.venta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarVenta", WrapperNamespace="http://ventas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.VentaWS.venta venta;
        
        public modificarVentaRequest() {
        }
        
        public modificarVentaRequest(WearDropWA.VentaWS.venta venta) {
            this.venta = venta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarVentaResponse", WrapperNamespace="http://ventas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarVentaResponse() {
        }
        
        public modificarVentaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVenta", WrapperNamespace="http://ventas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.VentaWS.venta venta;
        
        public insertarVentaRequest() {
        }
        
        public insertarVentaRequest(WearDropWA.VentaWS.venta venta) {
            this.venta = venta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVentaResponse", WrapperNamespace="http://ventas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ventas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarVentaResponse() {
        }
        
        public insertarVentaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VentaWSChannel : WearDropWA.VentaWS.VentaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentaWSClient : System.ServiceModel.ClientBase<WearDropWA.VentaWS.VentaWS>, WearDropWA.VentaWS.VentaWS {
        
        public VentaWSClient() {
        }
        
        public VentaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VentaWS.eliminarVentaResponse WearDropWA.VentaWS.VentaWS.eliminarVenta(WearDropWA.VentaWS.eliminarVentaRequest request) {
            return base.Channel.eliminarVenta(request);
        }
        
        public int eliminarVenta(int idVenta) {
            WearDropWA.VentaWS.eliminarVentaRequest inValue = new WearDropWA.VentaWS.eliminarVentaRequest();
            inValue.idVenta = idVenta;
            WearDropWA.VentaWS.eliminarVentaResponse retVal = ((WearDropWA.VentaWS.VentaWS)(this)).eliminarVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VentaWS.eliminarVentaResponse> WearDropWA.VentaWS.VentaWS.eliminarVentaAsync(WearDropWA.VentaWS.eliminarVentaRequest request) {
            return base.Channel.eliminarVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VentaWS.eliminarVentaResponse> eliminarVentaAsync(int idVenta) {
            WearDropWA.VentaWS.eliminarVentaRequest inValue = new WearDropWA.VentaWS.eliminarVentaRequest();
            inValue.idVenta = idVenta;
            return ((WearDropWA.VentaWS.VentaWS)(this)).eliminarVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VentaWS.listarVentasResponse WearDropWA.VentaWS.VentaWS.listarVentas(WearDropWA.VentaWS.listarVentasRequest request) {
            return base.Channel.listarVentas(request);
        }
        
        public WearDropWA.VentaWS.venta[] listarVentas() {
            WearDropWA.VentaWS.listarVentasRequest inValue = new WearDropWA.VentaWS.listarVentasRequest();
            WearDropWA.VentaWS.listarVentasResponse retVal = ((WearDropWA.VentaWS.VentaWS)(this)).listarVentas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VentaWS.listarVentasResponse> WearDropWA.VentaWS.VentaWS.listarVentasAsync(WearDropWA.VentaWS.listarVentasRequest request) {
            return base.Channel.listarVentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VentaWS.listarVentasResponse> listarVentasAsync() {
            WearDropWA.VentaWS.listarVentasRequest inValue = new WearDropWA.VentaWS.listarVentasRequest();
            return ((WearDropWA.VentaWS.VentaWS)(this)).listarVentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VentaWS.obtenerVentaPorIdResponse WearDropWA.VentaWS.VentaWS.obtenerVentaPorId(WearDropWA.VentaWS.obtenerVentaPorIdRequest request) {
            return base.Channel.obtenerVentaPorId(request);
        }
        
        public WearDropWA.VentaWS.venta obtenerVentaPorId(int idVenta) {
            WearDropWA.VentaWS.obtenerVentaPorIdRequest inValue = new WearDropWA.VentaWS.obtenerVentaPorIdRequest();
            inValue.idVenta = idVenta;
            WearDropWA.VentaWS.obtenerVentaPorIdResponse retVal = ((WearDropWA.VentaWS.VentaWS)(this)).obtenerVentaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VentaWS.obtenerVentaPorIdResponse> WearDropWA.VentaWS.VentaWS.obtenerVentaPorIdAsync(WearDropWA.VentaWS.obtenerVentaPorIdRequest request) {
            return base.Channel.obtenerVentaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VentaWS.obtenerVentaPorIdResponse> obtenerVentaPorIdAsync(int idVenta) {
            WearDropWA.VentaWS.obtenerVentaPorIdRequest inValue = new WearDropWA.VentaWS.obtenerVentaPorIdRequest();
            inValue.idVenta = idVenta;
            return ((WearDropWA.VentaWS.VentaWS)(this)).obtenerVentaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VentaWS.modificarVentaResponse WearDropWA.VentaWS.VentaWS.modificarVenta(WearDropWA.VentaWS.modificarVentaRequest request) {
            return base.Channel.modificarVenta(request);
        }
        
        public int modificarVenta(WearDropWA.VentaWS.venta venta) {
            WearDropWA.VentaWS.modificarVentaRequest inValue = new WearDropWA.VentaWS.modificarVentaRequest();
            inValue.venta = venta;
            WearDropWA.VentaWS.modificarVentaResponse retVal = ((WearDropWA.VentaWS.VentaWS)(this)).modificarVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VentaWS.modificarVentaResponse> WearDropWA.VentaWS.VentaWS.modificarVentaAsync(WearDropWA.VentaWS.modificarVentaRequest request) {
            return base.Channel.modificarVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VentaWS.modificarVentaResponse> modificarVentaAsync(WearDropWA.VentaWS.venta venta) {
            WearDropWA.VentaWS.modificarVentaRequest inValue = new WearDropWA.VentaWS.modificarVentaRequest();
            inValue.venta = venta;
            return ((WearDropWA.VentaWS.VentaWS)(this)).modificarVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VentaWS.insertarVentaResponse WearDropWA.VentaWS.VentaWS.insertarVenta(WearDropWA.VentaWS.insertarVentaRequest request) {
            return base.Channel.insertarVenta(request);
        }
        
        public int insertarVenta(WearDropWA.VentaWS.venta venta) {
            WearDropWA.VentaWS.insertarVentaRequest inValue = new WearDropWA.VentaWS.insertarVentaRequest();
            inValue.venta = venta;
            WearDropWA.VentaWS.insertarVentaResponse retVal = ((WearDropWA.VentaWS.VentaWS)(this)).insertarVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VentaWS.insertarVentaResponse> WearDropWA.VentaWS.VentaWS.insertarVentaAsync(WearDropWA.VentaWS.insertarVentaRequest request) {
            return base.Channel.insertarVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VentaWS.insertarVentaResponse> insertarVentaAsync(WearDropWA.VentaWS.venta venta) {
            WearDropWA.VentaWS.insertarVentaRequest inValue = new WearDropWA.VentaWS.insertarVentaRequest();
            inValue.venta = venta;
            return ((WearDropWA.VentaWS.VentaWS)(this)).insertarVentaAsync(inValue);
        }
    }
}
