//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.TipoCuentaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", ConfigurationName="TipoCuentaWS.TipoCuentaWS")]
    public interface TipoCuentaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/listarTiposCuentaReque" +
            "st", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/listarTiposCuentaRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.TipoCuentaWS.listarTiposCuentaResponse listarTiposCuenta(WearDropWA.TipoCuentaWS.listarTiposCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/listarTiposCuentaReque" +
            "st", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/listarTiposCuentaRespo" +
            "nse")]
        System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.listarTiposCuentaResponse> listarTiposCuentaAsync(WearDropWA.TipoCuentaWS.listarTiposCuentaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/modificarTipoCuentaReq" +
            "uest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/modificarTipoCuentaRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.TipoCuentaWS.modificarTipoCuentaResponse modificarTipoCuenta(WearDropWA.TipoCuentaWS.modificarTipoCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/modificarTipoCuentaReq" +
            "uest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/modificarTipoCuentaRes" +
            "ponse")]
        System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.modificarTipoCuentaResponse> modificarTipoCuentaAsync(WearDropWA.TipoCuentaWS.modificarTipoCuentaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/insertarTipoCuentaRequ" +
            "est", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/insertarTipoCuentaResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.TipoCuentaWS.insertarTipoCuentaResponse insertarTipoCuenta(WearDropWA.TipoCuentaWS.insertarTipoCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/insertarTipoCuentaRequ" +
            "est", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/insertarTipoCuentaResp" +
            "onse")]
        System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.insertarTipoCuentaResponse> insertarTipoCuentaAsync(WearDropWA.TipoCuentaWS.insertarTipoCuentaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/eliminarTipoCuentaRequ" +
            "est", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/eliminarTipoCuentaResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.TipoCuentaWS.eliminarTipoCuentaResponse eliminarTipoCuenta(WearDropWA.TipoCuentaWS.eliminarTipoCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/eliminarTipoCuentaRequ" +
            "est", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/eliminarTipoCuentaResp" +
            "onse")]
        System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.eliminarTipoCuentaResponse> eliminarTipoCuentaAsync(WearDropWA.TipoCuentaWS.eliminarTipoCuentaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/obtenerTipoCuentaPorId" +
            "Request", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/obtenerTipoCuentaPorId" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdResponse obtenerTipoCuentaPorId(WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/obtenerTipoCuentaPorId" +
            "Request", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/TipoCuentaWS/obtenerTipoCuentaPorId" +
            "Response")]
        System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdResponse> obtenerTipoCuentaPorIdAsync(WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/")]
    public partial class tipoCuenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idTipoCuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTipoCuenta {
            get {
                return this.idTipoCuentaField;
            }
            set {
                this.idTipoCuentaField = value;
                this.RaisePropertyChanged("idTipoCuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTiposCuenta", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTiposCuentaRequest {
        
        public listarTiposCuentaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTiposCuentaResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTiposCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.TipoCuentaWS.tipoCuenta[] @return;
        
        public listarTiposCuentaResponse() {
        }
        
        public listarTiposCuentaResponse(WearDropWA.TipoCuentaWS.tipoCuenta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTipoCuenta", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTipoCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.TipoCuentaWS.tipoCuenta tipoCuenta;
        
        public modificarTipoCuentaRequest() {
        }
        
        public modificarTipoCuentaRequest(WearDropWA.TipoCuentaWS.tipoCuenta tipoCuenta) {
            this.tipoCuenta = tipoCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTipoCuentaResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTipoCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTipoCuentaResponse() {
        }
        
        public modificarTipoCuentaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoCuenta", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.TipoCuentaWS.tipoCuenta tipoCuenta;
        
        public insertarTipoCuentaRequest() {
        }
        
        public insertarTipoCuentaRequest(WearDropWA.TipoCuentaWS.tipoCuenta tipoCuenta) {
            this.tipoCuenta = tipoCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoCuentaResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTipoCuentaResponse() {
        }
        
        public insertarTipoCuentaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTipoCuenta", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTipoCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoCuenta;
        
        public eliminarTipoCuentaRequest() {
        }
        
        public eliminarTipoCuentaRequest(int idTipoCuenta) {
            this.idTipoCuenta = idTipoCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTipoCuentaResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTipoCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTipoCuentaResponse() {
        }
        
        public eliminarTipoCuentaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTipoCuentaPorId", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerTipoCuentaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoCuenta;
        
        public obtenerTipoCuentaPorIdRequest() {
        }
        
        public obtenerTipoCuentaPorIdRequest(int idTipoCuenta) {
            this.idTipoCuenta = idTipoCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTipoCuentaPorIdResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerTipoCuentaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.TipoCuentaWS.tipoCuenta @return;
        
        public obtenerTipoCuentaPorIdResponse() {
        }
        
        public obtenerTipoCuentaPorIdResponse(WearDropWA.TipoCuentaWS.tipoCuenta @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoCuentaWSChannel : WearDropWA.TipoCuentaWS.TipoCuentaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoCuentaWSClient : System.ServiceModel.ClientBase<WearDropWA.TipoCuentaWS.TipoCuentaWS>, WearDropWA.TipoCuentaWS.TipoCuentaWS {
        
        public TipoCuentaWSClient() {
        }
        
        public TipoCuentaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoCuentaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCuentaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCuentaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.TipoCuentaWS.listarTiposCuentaResponse WearDropWA.TipoCuentaWS.TipoCuentaWS.listarTiposCuenta(WearDropWA.TipoCuentaWS.listarTiposCuentaRequest request) {
            return base.Channel.listarTiposCuenta(request);
        }
        
        public WearDropWA.TipoCuentaWS.tipoCuenta[] listarTiposCuenta() {
            WearDropWA.TipoCuentaWS.listarTiposCuentaRequest inValue = new WearDropWA.TipoCuentaWS.listarTiposCuentaRequest();
            WearDropWA.TipoCuentaWS.listarTiposCuentaResponse retVal = ((WearDropWA.TipoCuentaWS.TipoCuentaWS)(this)).listarTiposCuenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.listarTiposCuentaResponse> WearDropWA.TipoCuentaWS.TipoCuentaWS.listarTiposCuentaAsync(WearDropWA.TipoCuentaWS.listarTiposCuentaRequest request) {
            return base.Channel.listarTiposCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.listarTiposCuentaResponse> listarTiposCuentaAsync() {
            WearDropWA.TipoCuentaWS.listarTiposCuentaRequest inValue = new WearDropWA.TipoCuentaWS.listarTiposCuentaRequest();
            return ((WearDropWA.TipoCuentaWS.TipoCuentaWS)(this)).listarTiposCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.TipoCuentaWS.modificarTipoCuentaResponse WearDropWA.TipoCuentaWS.TipoCuentaWS.modificarTipoCuenta(WearDropWA.TipoCuentaWS.modificarTipoCuentaRequest request) {
            return base.Channel.modificarTipoCuenta(request);
        }
        
        public int modificarTipoCuenta(WearDropWA.TipoCuentaWS.tipoCuenta tipoCuenta) {
            WearDropWA.TipoCuentaWS.modificarTipoCuentaRequest inValue = new WearDropWA.TipoCuentaWS.modificarTipoCuentaRequest();
            inValue.tipoCuenta = tipoCuenta;
            WearDropWA.TipoCuentaWS.modificarTipoCuentaResponse retVal = ((WearDropWA.TipoCuentaWS.TipoCuentaWS)(this)).modificarTipoCuenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.modificarTipoCuentaResponse> WearDropWA.TipoCuentaWS.TipoCuentaWS.modificarTipoCuentaAsync(WearDropWA.TipoCuentaWS.modificarTipoCuentaRequest request) {
            return base.Channel.modificarTipoCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.modificarTipoCuentaResponse> modificarTipoCuentaAsync(WearDropWA.TipoCuentaWS.tipoCuenta tipoCuenta) {
            WearDropWA.TipoCuentaWS.modificarTipoCuentaRequest inValue = new WearDropWA.TipoCuentaWS.modificarTipoCuentaRequest();
            inValue.tipoCuenta = tipoCuenta;
            return ((WearDropWA.TipoCuentaWS.TipoCuentaWS)(this)).modificarTipoCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.TipoCuentaWS.insertarTipoCuentaResponse WearDropWA.TipoCuentaWS.TipoCuentaWS.insertarTipoCuenta(WearDropWA.TipoCuentaWS.insertarTipoCuentaRequest request) {
            return base.Channel.insertarTipoCuenta(request);
        }
        
        public int insertarTipoCuenta(WearDropWA.TipoCuentaWS.tipoCuenta tipoCuenta) {
            WearDropWA.TipoCuentaWS.insertarTipoCuentaRequest inValue = new WearDropWA.TipoCuentaWS.insertarTipoCuentaRequest();
            inValue.tipoCuenta = tipoCuenta;
            WearDropWA.TipoCuentaWS.insertarTipoCuentaResponse retVal = ((WearDropWA.TipoCuentaWS.TipoCuentaWS)(this)).insertarTipoCuenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.insertarTipoCuentaResponse> WearDropWA.TipoCuentaWS.TipoCuentaWS.insertarTipoCuentaAsync(WearDropWA.TipoCuentaWS.insertarTipoCuentaRequest request) {
            return base.Channel.insertarTipoCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.insertarTipoCuentaResponse> insertarTipoCuentaAsync(WearDropWA.TipoCuentaWS.tipoCuenta tipoCuenta) {
            WearDropWA.TipoCuentaWS.insertarTipoCuentaRequest inValue = new WearDropWA.TipoCuentaWS.insertarTipoCuentaRequest();
            inValue.tipoCuenta = tipoCuenta;
            return ((WearDropWA.TipoCuentaWS.TipoCuentaWS)(this)).insertarTipoCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.TipoCuentaWS.eliminarTipoCuentaResponse WearDropWA.TipoCuentaWS.TipoCuentaWS.eliminarTipoCuenta(WearDropWA.TipoCuentaWS.eliminarTipoCuentaRequest request) {
            return base.Channel.eliminarTipoCuenta(request);
        }
        
        public int eliminarTipoCuenta(int idTipoCuenta) {
            WearDropWA.TipoCuentaWS.eliminarTipoCuentaRequest inValue = new WearDropWA.TipoCuentaWS.eliminarTipoCuentaRequest();
            inValue.idTipoCuenta = idTipoCuenta;
            WearDropWA.TipoCuentaWS.eliminarTipoCuentaResponse retVal = ((WearDropWA.TipoCuentaWS.TipoCuentaWS)(this)).eliminarTipoCuenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.eliminarTipoCuentaResponse> WearDropWA.TipoCuentaWS.TipoCuentaWS.eliminarTipoCuentaAsync(WearDropWA.TipoCuentaWS.eliminarTipoCuentaRequest request) {
            return base.Channel.eliminarTipoCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.eliminarTipoCuentaResponse> eliminarTipoCuentaAsync(int idTipoCuenta) {
            WearDropWA.TipoCuentaWS.eliminarTipoCuentaRequest inValue = new WearDropWA.TipoCuentaWS.eliminarTipoCuentaRequest();
            inValue.idTipoCuenta = idTipoCuenta;
            return ((WearDropWA.TipoCuentaWS.TipoCuentaWS)(this)).eliminarTipoCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdResponse WearDropWA.TipoCuentaWS.TipoCuentaWS.obtenerTipoCuentaPorId(WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdRequest request) {
            return base.Channel.obtenerTipoCuentaPorId(request);
        }
        
        public WearDropWA.TipoCuentaWS.tipoCuenta obtenerTipoCuentaPorId(int idTipoCuenta) {
            WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdRequest inValue = new WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdRequest();
            inValue.idTipoCuenta = idTipoCuenta;
            WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdResponse retVal = ((WearDropWA.TipoCuentaWS.TipoCuentaWS)(this)).obtenerTipoCuentaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdResponse> WearDropWA.TipoCuentaWS.TipoCuentaWS.obtenerTipoCuentaPorIdAsync(WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdRequest request) {
            return base.Channel.obtenerTipoCuentaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdResponse> obtenerTipoCuentaPorIdAsync(int idTipoCuenta) {
            WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdRequest inValue = new WearDropWA.TipoCuentaWS.obtenerTipoCuentaPorIdRequest();
            inValue.idTipoCuenta = idTipoCuenta;
            return ((WearDropWA.TipoCuentaWS.TipoCuentaWS)(this)).obtenerTipoCuentaPorIdAsync(inValue);
        }
    }
}
