//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.CuentaUsuarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", ConfigurationName="CuentaUsuarioWS.CuentaUsuarioWS")]
    public interface CuentaUsuarioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/modificarCuentaUsua" +
            "rioRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/modificarCuentaUsua" +
            "rioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioResponse modificarCuentaUsuario(WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/modificarCuentaUsua" +
            "rioRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/modificarCuentaUsua" +
            "rioResponse")]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioResponse> modificarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/listarCuentasUsuari" +
            "oRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/listarCuentasUsuari" +
            "oResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioResponse listarCuentasUsuario(WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/listarCuentasUsuari" +
            "oRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/listarCuentasUsuari" +
            "oResponse")]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioResponse> listarCuentasUsuarioAsync(WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/insertarCuentaUsuar" +
            "ioRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/insertarCuentaUsuar" +
            "ioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioResponse insertarCuentaUsuario(WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/insertarCuentaUsuar" +
            "ioRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/insertarCuentaUsuar" +
            "ioResponse")]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioResponse> insertarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/eliminarCuentaUsuar" +
            "ioRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/eliminarCuentaUsuar" +
            "ioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioResponse eliminarCuentaUsuario(WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/eliminarCuentaUsuar" +
            "ioRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/eliminarCuentaUsuar" +
            "ioResponse")]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioResponse> eliminarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/cambiarContrasenaCo" +
            "nTokenRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/cambiarContrasenaCo" +
            "nTokenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenResponse cambiarContrasenaConToken(WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/cambiarContrasenaCo" +
            "nTokenRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/cambiarContrasenaCo" +
            "nTokenResponse")]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenResponse> cambiarContrasenaConTokenAsync(WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/obtenerCuentaUsuari" +
            "oPorIdRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/obtenerCuentaUsuari" +
            "oPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdResponse obtenerCuentaUsuarioPorId(WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/obtenerCuentaUsuari" +
            "oPorIdRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/obtenerCuentaUsuari" +
            "oPorIdResponse")]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdResponse> obtenerCuentaUsuarioPorIdAsync(WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/verificarCuentaUsua" +
            "rioRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/verificarCuentaUsua" +
            "rioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioResponse verificarCuentaUsuario(WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/verificarCuentaUsua" +
            "rioRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/verificarCuentaUsua" +
            "rioResponse")]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioResponse> verificarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/validarTokenRecuper" +
            "acionRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/validarTokenRecuper" +
            "acionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionResponse validarTokenRecuperacion(WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/validarTokenRecuper" +
            "acionRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/validarTokenRecuper" +
            "acionResponse")]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionResponse> validarTokenRecuperacionAsync(WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/solicitarRecuperaci" +
            "onContrasenaRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/solicitarRecuperaci" +
            "onContrasenaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaResponse solicitarRecuperacionContrasena(WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/solicitarRecuperaci" +
            "onContrasenaRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/CuentaUsuarioWS/solicitarRecuperaci" +
            "onContrasenaResponse")]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaResponse> solicitarRecuperacionContrasenaAsync(WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/")]
    public partial class cuentaUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string contrasenhaField;
        
        private string emailField;
        
        private empleado empleadoField;
        
        private int idCuentaField;
        
        private tipoCuenta tipoField;
        
        private System.DateTime tokenExpiracionField;
        
        private bool tokenExpiracionFieldSpecified;
        
        private string tokenRecuperacionField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("empleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCuenta {
            get {
                return this.idCuentaField;
            }
            set {
                this.idCuentaField = value;
                this.RaisePropertyChanged("idCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoCuenta tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime tokenExpiracion {
            get {
                return this.tokenExpiracionField;
            }
            set {
                this.tokenExpiracionField = value;
                this.RaisePropertyChanged("tokenExpiracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tokenExpiracionSpecified {
            get {
                return this.tokenExpiracionFieldSpecified;
            }
            set {
                this.tokenExpiracionFieldSpecified = value;
                this.RaisePropertyChanged("tokenExpiracionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tokenRecuperacion {
            get {
                return this.tokenRecuperacionField;
            }
            set {
                this.tokenRecuperacionField = value;
                this.RaisePropertyChanged("tokenRecuperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/")]
    public partial class empleado : persona {
        
        private bool activoField;
        
        private cargo cargoAsignadoField;
        
        private int idEmpleadoField;
        
        private double sueldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cargo cargoAsignado {
            get {
                return this.cargoAsignadoField;
            }
            set {
                this.cargoAsignadoField = value;
                this.RaisePropertyChanged("cargoAsignado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                this.idEmpleadoField = value;
                this.RaisePropertyChanged("idEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double sueldo {
            get {
                return this.sueldoField;
            }
            set {
                this.sueldoField = value;
                this.RaisePropertyChanged("sueldo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/")]
    public partial class cargo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort abreviaturaField;
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idCargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
                this.RaisePropertyChanged("abreviatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCargo {
            get {
                return this.idCargoField;
            }
            set {
                this.idCargoField = value;
                this.RaisePropertyChanged("idCargo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/")]
    public partial class tipoCuenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idTipoCuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTipoCuenta {
            get {
                return this.idTipoCuentaField;
            }
            set {
                this.idTipoCuentaField = value;
                this.RaisePropertyChanged("idTipoCuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dniField;
        
        private ushort generoField;
        
        private int idPersonaField;
        
        private string nombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCuentaUsuario", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCuentaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CuentaUsuarioWS.cuentaUsuario cuentaUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modo;
        
        public modificarCuentaUsuarioRequest() {
        }
        
        public modificarCuentaUsuarioRequest(WearDropWA.CuentaUsuarioWS.cuentaUsuario cuentaUsuario, string modo) {
            this.cuentaUsuario = cuentaUsuario;
            this.modo = modo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCuentaUsuarioResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCuentaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCuentaUsuarioResponse() {
        }
        
        public modificarCuentaUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCuentasUsuario", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCuentasUsuarioRequest {
        
        public listarCuentasUsuarioRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCuentasUsuarioResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCuentasUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CuentaUsuarioWS.cuentaUsuario[] @return;
        
        public listarCuentasUsuarioResponse() {
        }
        
        public listarCuentasUsuarioResponse(WearDropWA.CuentaUsuarioWS.cuentaUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCuentaUsuario", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCuentaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CuentaUsuarioWS.cuentaUsuario cuentaUsuario;
        
        public insertarCuentaUsuarioRequest() {
        }
        
        public insertarCuentaUsuarioRequest(WearDropWA.CuentaUsuarioWS.cuentaUsuario cuentaUsuario) {
            this.cuentaUsuario = cuentaUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCuentaUsuarioResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCuentaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCuentaUsuarioResponse() {
        }
        
        public insertarCuentaUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuentaUsuario", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCuentaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCuentaUsuario;
        
        public eliminarCuentaUsuarioRequest() {
        }
        
        public eliminarCuentaUsuarioRequest(int idCuentaUsuario) {
            this.idCuentaUsuario = idCuentaUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuentaUsuarioResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCuentaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCuentaUsuarioResponse() {
        }
        
        public eliminarCuentaUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambiarContrasenaConToken", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class cambiarContrasenaConTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuevaContrasena;
        
        public cambiarContrasenaConTokenRequest() {
        }
        
        public cambiarContrasenaConTokenRequest(string token, string nuevaContrasena) {
            this.token = token;
            this.nuevaContrasena = nuevaContrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambiarContrasenaConTokenResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class cambiarContrasenaConTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public cambiarContrasenaConTokenResponse() {
        }
        
        public cambiarContrasenaConTokenResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentaUsuarioPorId", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentaUsuarioPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCuentaUsuario;
        
        public obtenerCuentaUsuarioPorIdRequest() {
        }
        
        public obtenerCuentaUsuarioPorIdRequest(int idCuentaUsuario) {
            this.idCuentaUsuario = idCuentaUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentaUsuarioPorIdResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentaUsuarioPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CuentaUsuarioWS.cuentaUsuario @return;
        
        public obtenerCuentaUsuarioPorIdResponse() {
        }
        
        public obtenerCuentaUsuarioPorIdResponse(WearDropWA.CuentaUsuarioWS.cuentaUsuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarCuentaUsuario", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class verificarCuentaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CuentaUsuarioWS.cuentaUsuario CuentaUsuario;
        
        public verificarCuentaUsuarioRequest() {
        }
        
        public verificarCuentaUsuarioRequest(WearDropWA.CuentaUsuarioWS.cuentaUsuario CuentaUsuario) {
            this.CuentaUsuario = CuentaUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarCuentaUsuarioResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class verificarCuentaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public verificarCuentaUsuarioResponse() {
        }
        
        public verificarCuentaUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarTokenRecuperacion", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class validarTokenRecuperacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public validarTokenRecuperacionRequest() {
        }
        
        public validarTokenRecuperacionRequest(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarTokenRecuperacionResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class validarTokenRecuperacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CuentaUsuarioWS.cuentaUsuario @return;
        
        public validarTokenRecuperacionResponse() {
        }
        
        public validarTokenRecuperacionResponse(WearDropWA.CuentaUsuarioWS.cuentaUsuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarRecuperacionContrasena", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class solicitarRecuperacionContrasenaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public solicitarRecuperacionContrasenaRequest() {
        }
        
        public solicitarRecuperacionContrasenaRequest(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarRecuperacionContrasenaResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class solicitarRecuperacionContrasenaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public solicitarRecuperacionContrasenaResponse() {
        }
        
        public solicitarRecuperacionContrasenaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CuentaUsuarioWSChannel : WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuentaUsuarioWSClient : System.ServiceModel.ClientBase<WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS>, WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS {
        
        public CuentaUsuarioWSClient() {
        }
        
        public CuentaUsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuentaUsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaUsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaUsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioResponse WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.modificarCuentaUsuario(WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioRequest request) {
            return base.Channel.modificarCuentaUsuario(request);
        }
        
        public int modificarCuentaUsuario(WearDropWA.CuentaUsuarioWS.cuentaUsuario cuentaUsuario, string modo) {
            WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioRequest inValue = new WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioRequest();
            inValue.cuentaUsuario = cuentaUsuario;
            inValue.modo = modo;
            WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioResponse retVal = ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).modificarCuentaUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioResponse> WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.modificarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioRequest request) {
            return base.Channel.modificarCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioResponse> modificarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.cuentaUsuario cuentaUsuario, string modo) {
            WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioRequest inValue = new WearDropWA.CuentaUsuarioWS.modificarCuentaUsuarioRequest();
            inValue.cuentaUsuario = cuentaUsuario;
            inValue.modo = modo;
            return ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).modificarCuentaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioResponse WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.listarCuentasUsuario(WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioRequest request) {
            return base.Channel.listarCuentasUsuario(request);
        }
        
        public WearDropWA.CuentaUsuarioWS.cuentaUsuario[] listarCuentasUsuario() {
            WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioRequest inValue = new WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioRequest();
            WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioResponse retVal = ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).listarCuentasUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioResponse> WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.listarCuentasUsuarioAsync(WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioRequest request) {
            return base.Channel.listarCuentasUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioResponse> listarCuentasUsuarioAsync() {
            WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioRequest inValue = new WearDropWA.CuentaUsuarioWS.listarCuentasUsuarioRequest();
            return ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).listarCuentasUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioResponse WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.insertarCuentaUsuario(WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioRequest request) {
            return base.Channel.insertarCuentaUsuario(request);
        }
        
        public int insertarCuentaUsuario(WearDropWA.CuentaUsuarioWS.cuentaUsuario cuentaUsuario) {
            WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioRequest inValue = new WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioRequest();
            inValue.cuentaUsuario = cuentaUsuario;
            WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioResponse retVal = ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).insertarCuentaUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioResponse> WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.insertarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioRequest request) {
            return base.Channel.insertarCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioResponse> insertarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.cuentaUsuario cuentaUsuario) {
            WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioRequest inValue = new WearDropWA.CuentaUsuarioWS.insertarCuentaUsuarioRequest();
            inValue.cuentaUsuario = cuentaUsuario;
            return ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).insertarCuentaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioResponse WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.eliminarCuentaUsuario(WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioRequest request) {
            return base.Channel.eliminarCuentaUsuario(request);
        }
        
        public int eliminarCuentaUsuario(int idCuentaUsuario) {
            WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioRequest inValue = new WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioRequest();
            inValue.idCuentaUsuario = idCuentaUsuario;
            WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioResponse retVal = ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).eliminarCuentaUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioResponse> WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.eliminarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioRequest request) {
            return base.Channel.eliminarCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioResponse> eliminarCuentaUsuarioAsync(int idCuentaUsuario) {
            WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioRequest inValue = new WearDropWA.CuentaUsuarioWS.eliminarCuentaUsuarioRequest();
            inValue.idCuentaUsuario = idCuentaUsuario;
            return ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).eliminarCuentaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenResponse WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.cambiarContrasenaConToken(WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenRequest request) {
            return base.Channel.cambiarContrasenaConToken(request);
        }
        
        public bool cambiarContrasenaConToken(string token, string nuevaContrasena) {
            WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenRequest inValue = new WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenRequest();
            inValue.token = token;
            inValue.nuevaContrasena = nuevaContrasena;
            WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenResponse retVal = ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).cambiarContrasenaConToken(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenResponse> WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.cambiarContrasenaConTokenAsync(WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenRequest request) {
            return base.Channel.cambiarContrasenaConTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenResponse> cambiarContrasenaConTokenAsync(string token, string nuevaContrasena) {
            WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenRequest inValue = new WearDropWA.CuentaUsuarioWS.cambiarContrasenaConTokenRequest();
            inValue.token = token;
            inValue.nuevaContrasena = nuevaContrasena;
            return ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).cambiarContrasenaConTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdResponse WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.obtenerCuentaUsuarioPorId(WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdRequest request) {
            return base.Channel.obtenerCuentaUsuarioPorId(request);
        }
        
        public WearDropWA.CuentaUsuarioWS.cuentaUsuario obtenerCuentaUsuarioPorId(int idCuentaUsuario) {
            WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdRequest inValue = new WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdRequest();
            inValue.idCuentaUsuario = idCuentaUsuario;
            WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdResponse retVal = ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).obtenerCuentaUsuarioPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdResponse> WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdAsync(WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdRequest request) {
            return base.Channel.obtenerCuentaUsuarioPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdResponse> obtenerCuentaUsuarioPorIdAsync(int idCuentaUsuario) {
            WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdRequest inValue = new WearDropWA.CuentaUsuarioWS.obtenerCuentaUsuarioPorIdRequest();
            inValue.idCuentaUsuario = idCuentaUsuario;
            return ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).obtenerCuentaUsuarioPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioResponse WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.verificarCuentaUsuario(WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioRequest request) {
            return base.Channel.verificarCuentaUsuario(request);
        }
        
        public int verificarCuentaUsuario(WearDropWA.CuentaUsuarioWS.cuentaUsuario CuentaUsuario) {
            WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioRequest inValue = new WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioRequest();
            inValue.CuentaUsuario = CuentaUsuario;
            WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioResponse retVal = ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).verificarCuentaUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioResponse> WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.verificarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioRequest request) {
            return base.Channel.verificarCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioResponse> verificarCuentaUsuarioAsync(WearDropWA.CuentaUsuarioWS.cuentaUsuario CuentaUsuario) {
            WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioRequest inValue = new WearDropWA.CuentaUsuarioWS.verificarCuentaUsuarioRequest();
            inValue.CuentaUsuario = CuentaUsuario;
            return ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).verificarCuentaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionResponse WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.validarTokenRecuperacion(WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionRequest request) {
            return base.Channel.validarTokenRecuperacion(request);
        }
        
        public WearDropWA.CuentaUsuarioWS.cuentaUsuario validarTokenRecuperacion(string token) {
            WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionRequest inValue = new WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionRequest();
            inValue.token = token;
            WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionResponse retVal = ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).validarTokenRecuperacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionResponse> WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.validarTokenRecuperacionAsync(WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionRequest request) {
            return base.Channel.validarTokenRecuperacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionResponse> validarTokenRecuperacionAsync(string token) {
            WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionRequest inValue = new WearDropWA.CuentaUsuarioWS.validarTokenRecuperacionRequest();
            inValue.token = token;
            return ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).validarTokenRecuperacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaResponse WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.solicitarRecuperacionContrasena(WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaRequest request) {
            return base.Channel.solicitarRecuperacionContrasena(request);
        }
        
        public bool solicitarRecuperacionContrasena(string email) {
            WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaRequest inValue = new WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaRequest();
            inValue.email = email;
            WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaResponse retVal = ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).solicitarRecuperacionContrasena(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaResponse> WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS.solicitarRecuperacionContrasenaAsync(WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaRequest request) {
            return base.Channel.solicitarRecuperacionContrasenaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaResponse> solicitarRecuperacionContrasenaAsync(string email) {
            WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaRequest inValue = new WearDropWA.CuentaUsuarioWS.solicitarRecuperacionContrasenaRequest();
            inValue.email = email;
            return ((WearDropWA.CuentaUsuarioWS.CuentaUsuarioWS)(this)).solicitarRecuperacionContrasenaAsync(inValue);
        }
    }
}
