//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.EmpleadoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", ConfigurationName="EmpleadoWS.EmpleadoWS")]
    public interface EmpleadoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/obtenerEmpleadoPorIdRequ" +
            "est", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/obtenerEmpleadoPorIdResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdResponse obtenerEmpleadoPorId(WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/obtenerEmpleadoPorIdRequ" +
            "est", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/obtenerEmpleadoPorIdResp" +
            "onse")]
        System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdResponse> obtenerEmpleadoPorIdAsync(WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/insertarEmpleadoRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/insertarEmpleadoResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.EmpleadoWS.insertarEmpleadoResponse insertarEmpleado(WearDropWA.EmpleadoWS.insertarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/insertarEmpleadoRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/insertarEmpleadoResponse" +
            "")]
        System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.insertarEmpleadoResponse> insertarEmpleadoAsync(WearDropWA.EmpleadoWS.insertarEmpleadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/listarEmpleadosRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/listarEmpleadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.EmpleadoWS.listarEmpleadosResponse listarEmpleados(WearDropWA.EmpleadoWS.listarEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/listarEmpleadosRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/listarEmpleadosResponse")]
        System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.listarEmpleadosResponse> listarEmpleadosAsync(WearDropWA.EmpleadoWS.listarEmpleadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/modificarEmpleadoRequest" +
            "", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/modificarEmpleadoRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.EmpleadoWS.modificarEmpleadoResponse modificarEmpleado(WearDropWA.EmpleadoWS.modificarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/modificarEmpleadoRequest" +
            "", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/modificarEmpleadoRespons" +
            "e")]
        System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.modificarEmpleadoResponse> modificarEmpleadoAsync(WearDropWA.EmpleadoWS.modificarEmpleadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/eliminarEmpleadoRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/eliminarEmpleadoResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.EmpleadoWS.eliminarEmpleadoResponse eliminarEmpleado(WearDropWA.EmpleadoWS.eliminarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/eliminarEmpleadoRequest", ReplyAction="http://personal.services.weardrop.pucp.edu.pe/EmpleadoWS/eliminarEmpleadoResponse" +
            "")]
        System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.eliminarEmpleadoResponse> eliminarEmpleadoAsync(WearDropWA.EmpleadoWS.eliminarEmpleadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/")]
    public partial class empleado : persona {
        
        private bool activoField;
        
        private cargo cargoAsignadoField;
        
        private int idEmpleadoField;
        
        private double sueldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cargo cargoAsignado {
            get {
                return this.cargoAsignadoField;
            }
            set {
                this.cargoAsignadoField = value;
                this.RaisePropertyChanged("cargoAsignado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                this.idEmpleadoField = value;
                this.RaisePropertyChanged("idEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double sueldo {
            get {
                return this.sueldoField;
            }
            set {
                this.sueldoField = value;
                this.RaisePropertyChanged("sueldo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/")]
    public partial class cargo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort abreviaturaField;
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idCargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
                this.RaisePropertyChanged("abreviatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCargo {
            get {
                return this.idCargoField;
            }
            set {
                this.idCargoField = value;
                this.RaisePropertyChanged("idCargo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dniField;
        
        private ushort generoField;
        
        private int idPersonaField;
        
        private string nombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEmpleadoPorId", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEmpleadoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEmpleado;
        
        public obtenerEmpleadoPorIdRequest() {
        }
        
        public obtenerEmpleadoPorIdRequest(int idEmpleado) {
            this.idEmpleado = idEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEmpleadoPorIdResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEmpleadoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.EmpleadoWS.empleado @return;
        
        public obtenerEmpleadoPorIdResponse() {
        }
        
        public obtenerEmpleadoPorIdResponse(WearDropWA.EmpleadoWS.empleado @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpleado", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.EmpleadoWS.empleado empleado;
        
        public insertarEmpleadoRequest() {
        }
        
        public insertarEmpleadoRequest(WearDropWA.EmpleadoWS.empleado empleado) {
            this.empleado = empleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpleadoResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEmpleadoResponse() {
        }
        
        public insertarEmpleadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpleados", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpleadosRequest {
        
        public listarEmpleadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpleadosResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.EmpleadoWS.empleado[] @return;
        
        public listarEmpleadosResponse() {
        }
        
        public listarEmpleadosResponse(WearDropWA.EmpleadoWS.empleado[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEmpleado", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.EmpleadoWS.empleado empleado;
        
        public modificarEmpleadoRequest() {
        }
        
        public modificarEmpleadoRequest(WearDropWA.EmpleadoWS.empleado empleado) {
            this.empleado = empleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEmpleadoResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarEmpleadoResponse() {
        }
        
        public modificarEmpleadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpleado", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEmpleado;
        
        public eliminarEmpleadoRequest() {
        }
        
        public eliminarEmpleadoRequest(int idEmpleado) {
            this.idEmpleado = idEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpleadoResponse", WrapperNamespace="http://personal.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://personal.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarEmpleadoResponse() {
        }
        
        public eliminarEmpleadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpleadoWSChannel : WearDropWA.EmpleadoWS.EmpleadoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoWSClient : System.ServiceModel.ClientBase<WearDropWA.EmpleadoWS.EmpleadoWS>, WearDropWA.EmpleadoWS.EmpleadoWS {
        
        public EmpleadoWSClient() {
        }
        
        public EmpleadoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdResponse WearDropWA.EmpleadoWS.EmpleadoWS.obtenerEmpleadoPorId(WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdRequest request) {
            return base.Channel.obtenerEmpleadoPorId(request);
        }
        
        public WearDropWA.EmpleadoWS.empleado obtenerEmpleadoPorId(int idEmpleado) {
            WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdRequest inValue = new WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdRequest();
            inValue.idEmpleado = idEmpleado;
            WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdResponse retVal = ((WearDropWA.EmpleadoWS.EmpleadoWS)(this)).obtenerEmpleadoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdResponse> WearDropWA.EmpleadoWS.EmpleadoWS.obtenerEmpleadoPorIdAsync(WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdRequest request) {
            return base.Channel.obtenerEmpleadoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdResponse> obtenerEmpleadoPorIdAsync(int idEmpleado) {
            WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdRequest inValue = new WearDropWA.EmpleadoWS.obtenerEmpleadoPorIdRequest();
            inValue.idEmpleado = idEmpleado;
            return ((WearDropWA.EmpleadoWS.EmpleadoWS)(this)).obtenerEmpleadoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.EmpleadoWS.insertarEmpleadoResponse WearDropWA.EmpleadoWS.EmpleadoWS.insertarEmpleado(WearDropWA.EmpleadoWS.insertarEmpleadoRequest request) {
            return base.Channel.insertarEmpleado(request);
        }
        
        public int insertarEmpleado(WearDropWA.EmpleadoWS.empleado empleado) {
            WearDropWA.EmpleadoWS.insertarEmpleadoRequest inValue = new WearDropWA.EmpleadoWS.insertarEmpleadoRequest();
            inValue.empleado = empleado;
            WearDropWA.EmpleadoWS.insertarEmpleadoResponse retVal = ((WearDropWA.EmpleadoWS.EmpleadoWS)(this)).insertarEmpleado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.insertarEmpleadoResponse> WearDropWA.EmpleadoWS.EmpleadoWS.insertarEmpleadoAsync(WearDropWA.EmpleadoWS.insertarEmpleadoRequest request) {
            return base.Channel.insertarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.insertarEmpleadoResponse> insertarEmpleadoAsync(WearDropWA.EmpleadoWS.empleado empleado) {
            WearDropWA.EmpleadoWS.insertarEmpleadoRequest inValue = new WearDropWA.EmpleadoWS.insertarEmpleadoRequest();
            inValue.empleado = empleado;
            return ((WearDropWA.EmpleadoWS.EmpleadoWS)(this)).insertarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.EmpleadoWS.listarEmpleadosResponse WearDropWA.EmpleadoWS.EmpleadoWS.listarEmpleados(WearDropWA.EmpleadoWS.listarEmpleadosRequest request) {
            return base.Channel.listarEmpleados(request);
        }
        
        public WearDropWA.EmpleadoWS.empleado[] listarEmpleados() {
            WearDropWA.EmpleadoWS.listarEmpleadosRequest inValue = new WearDropWA.EmpleadoWS.listarEmpleadosRequest();
            WearDropWA.EmpleadoWS.listarEmpleadosResponse retVal = ((WearDropWA.EmpleadoWS.EmpleadoWS)(this)).listarEmpleados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.listarEmpleadosResponse> WearDropWA.EmpleadoWS.EmpleadoWS.listarEmpleadosAsync(WearDropWA.EmpleadoWS.listarEmpleadosRequest request) {
            return base.Channel.listarEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.listarEmpleadosResponse> listarEmpleadosAsync() {
            WearDropWA.EmpleadoWS.listarEmpleadosRequest inValue = new WearDropWA.EmpleadoWS.listarEmpleadosRequest();
            return ((WearDropWA.EmpleadoWS.EmpleadoWS)(this)).listarEmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.EmpleadoWS.modificarEmpleadoResponse WearDropWA.EmpleadoWS.EmpleadoWS.modificarEmpleado(WearDropWA.EmpleadoWS.modificarEmpleadoRequest request) {
            return base.Channel.modificarEmpleado(request);
        }
        
        public int modificarEmpleado(WearDropWA.EmpleadoWS.empleado empleado) {
            WearDropWA.EmpleadoWS.modificarEmpleadoRequest inValue = new WearDropWA.EmpleadoWS.modificarEmpleadoRequest();
            inValue.empleado = empleado;
            WearDropWA.EmpleadoWS.modificarEmpleadoResponse retVal = ((WearDropWA.EmpleadoWS.EmpleadoWS)(this)).modificarEmpleado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.modificarEmpleadoResponse> WearDropWA.EmpleadoWS.EmpleadoWS.modificarEmpleadoAsync(WearDropWA.EmpleadoWS.modificarEmpleadoRequest request) {
            return base.Channel.modificarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.modificarEmpleadoResponse> modificarEmpleadoAsync(WearDropWA.EmpleadoWS.empleado empleado) {
            WearDropWA.EmpleadoWS.modificarEmpleadoRequest inValue = new WearDropWA.EmpleadoWS.modificarEmpleadoRequest();
            inValue.empleado = empleado;
            return ((WearDropWA.EmpleadoWS.EmpleadoWS)(this)).modificarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.EmpleadoWS.eliminarEmpleadoResponse WearDropWA.EmpleadoWS.EmpleadoWS.eliminarEmpleado(WearDropWA.EmpleadoWS.eliminarEmpleadoRequest request) {
            return base.Channel.eliminarEmpleado(request);
        }
        
        public int eliminarEmpleado(int idEmpleado) {
            WearDropWA.EmpleadoWS.eliminarEmpleadoRequest inValue = new WearDropWA.EmpleadoWS.eliminarEmpleadoRequest();
            inValue.idEmpleado = idEmpleado;
            WearDropWA.EmpleadoWS.eliminarEmpleadoResponse retVal = ((WearDropWA.EmpleadoWS.EmpleadoWS)(this)).eliminarEmpleado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.eliminarEmpleadoResponse> WearDropWA.EmpleadoWS.EmpleadoWS.eliminarEmpleadoAsync(WearDropWA.EmpleadoWS.eliminarEmpleadoRequest request) {
            return base.Channel.eliminarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.EmpleadoWS.eliminarEmpleadoResponse> eliminarEmpleadoAsync(int idEmpleado) {
            WearDropWA.EmpleadoWS.eliminarEmpleadoRequest inValue = new WearDropWA.EmpleadoWS.eliminarEmpleadoRequest();
            inValue.idEmpleado = idEmpleado;
            return ((WearDropWA.EmpleadoWS.EmpleadoWS)(this)).eliminarEmpleadoAsync(inValue);
        }
    }
}
